# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\F\Work\python\bioinfo_excercise\PhyloSuite\codes\PhyloSuite_gitee\PhyloSuite\uifiles\ASTRAL.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ASTRAL(object):
    def setupUi(self, ASTRAL):
        ASTRAL.setObjectName("ASTRAL")
        ASTRAL.resize(1065, 863)
        ASTRAL.setStyleSheet("")
        ASTRAL.setSizeGripEnabled(True)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ASTRAL)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(ASTRAL)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 0, 0, 1, 1)
        self.comboBox_18 = ListQCombobox(self.groupBox_4)
        self.comboBox_18.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_18.sizePolicy().hasHeightForWidth())
        self.comboBox_18.setSizePolicy(sizePolicy)
        self.comboBox_18.setAcceptDrops(True)
        self.comboBox_18.setEditable(True)
        self.comboBox_18.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_18.setObjectName("comboBox_18")
        self.gridLayout.addWidget(self.comboBox_18, 0, 1, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton.setEnabled(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/resourses/M.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 0, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_7.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(30, 26))
        self.pushButton_7.setMaximumSize(QtCore.QSize(30, 26))
        self.pushButton_7.setStyleSheet("")
        self.pushButton_7.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/picture/resourses/Open_folder_add_512px_1186192_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 3, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 1, 0, 1, 1)
        self.comboBox_19 = ListQCombobox(self.groupBox_4)
        self.comboBox_19.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_19.sizePolicy().hasHeightForWidth())
        self.comboBox_19.setSizePolicy(sizePolicy)
        self.comboBox_19.setAcceptDrops(True)
        self.comboBox_19.setEditable(True)
        self.comboBox_19.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_19.setObjectName("comboBox_19")
        self.gridLayout.addWidget(self.comboBox_19, 1, 1, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton_2.setEnabled(False)
        self.toolButton_2.setIcon(icon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout.addWidget(self.toolButton_2, 1, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_8.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(30, 26))
        self.pushButton_8.setMaximumSize(QtCore.QSize(30, 26))
        self.pushButton_8.setStyleSheet("")
        self.pushButton_8.setText("")
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 1, 3, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 2, 0, 1, 1)
        self.comboBox_20 = ListQCombobox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_20.sizePolicy().hasHeightForWidth())
        self.comboBox_20.setSizePolicy(sizePolicy)
        self.comboBox_20.setAcceptDrops(True)
        self.comboBox_20.setEditable(True)
        self.comboBox_20.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_20.setObjectName("comboBox_20")
        self.gridLayout.addWidget(self.comboBox_20, 2, 1, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton_3.setIcon(icon)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout.addWidget(self.toolButton_3, 2, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.lineEdit_2 = InputQLineEdit(self.groupBox_4)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 3, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_4.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 3, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.lineEdit_3 = InputQLineEdit(self.groupBox_4)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 4, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_5.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 4, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_2 = ClickedLableGif(self.groupBox_4)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(ASTRAL)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_13 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_13.sizePolicy().hasHeightForWidth())
        self.comboBox_13.setSizePolicy(sizePolicy)
        self.comboBox_13.setMinimumSize(QtCore.QSize(114, 26))
        self.comboBox_13.setMaximumSize(QtCore.QSize(16777215, 26))
        self.comboBox_13.setStyleSheet("")
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_13, 9, 1, 1, 8)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 4, 4, 1, 5)
        self.comboBox_16 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_16.sizePolicy().hasHeightForWidth())
        self.comboBox_16.setSizePolicy(sizePolicy)
        self.comboBox_16.setMinimumSize(QtCore.QSize(114, 26))
        self.comboBox_16.setMaximumSize(QtCore.QSize(16777215, 26))
        self.comboBox_16.setStyleSheet("")
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_16, 6, 4, 1, 5)
        self.label_29 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 5, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox.setMaximum(999999999)
        self.spinBox.setSingleStep(1000)
        self.spinBox.setProperty("value", 10000)
        self.spinBox.setDisplayIntegerBase(10)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 5, 1, 1, 2)
        self.comboBox_12 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_12.sizePolicy().hasHeightForWidth())
        self.comboBox_12.setSizePolicy(sizePolicy)
        self.comboBox_12.setMinimumSize(QtCore.QSize(114, 26))
        self.comboBox_12.setMaximumSize(QtCore.QSize(16777215, 26))
        self.comboBox_12.setStyleSheet("")
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_12, 10, 1, 1, 2)
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        self.comboBox_6.setMinimumSize(QtCore.QSize(13, 26))
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout_2.addWidget(self.comboBox_6, 3, 4, 1, 5)
        self.comboBox_14 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_14.sizePolicy().hasHeightForWidth())
        self.comboBox_14.setSizePolicy(sizePolicy)
        self.comboBox_14.setMinimumSize(QtCore.QSize(114, 26))
        self.comboBox_14.setMaximumSize(QtCore.QSize(16777215, 26))
        self.comboBox_14.setStyleSheet("")
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_14, 4, 1, 1, 2)
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 10, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 9, 0, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_10.sizePolicy().hasHeightForWidth())
        self.comboBox_10.setSizePolicy(sizePolicy)
        self.comboBox_10.setMinimumSize(QtCore.QSize(114, 26))
        self.comboBox_10.setMaximumSize(QtCore.QSize(16777215, 26))
        self.comboBox_10.setStyleSheet("")
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_10, 2, 1, 1, 2)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_2.setMaximum(999999999)
        self.spinBox_2.setSingleStep(1000)
        self.spinBox_2.setProperty("value", 20)
        self.spinBox_2.setDisplayIntegerBase(10)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_2.addWidget(self.spinBox_2, 5, 4, 1, 5)
        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 7, 3, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_9.sizePolicy().hasHeightForWidth())
        self.comboBox_9.setSizePolicy(sizePolicy)
        self.comboBox_9.setMinimumSize(QtCore.QSize(114, 26))
        self.comboBox_9.setMaximumSize(QtCore.QSize(16777215, 26))
        self.comboBox_9.setStyleSheet("")
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_9, 0, 1, 1, 8)
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 4, 0, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_2.setDecimals(3)
        self.doubleSpinBox_2.setMaximum(99999999999999.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_2.addWidget(self.doubleSpinBox_2, 11, 1, 1, 2)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_4.setDecimals(3)
        self.doubleSpinBox_4.setMaximum(99999999999999.0)
        self.doubleSpinBox_4.setProperty("value", 0.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_2.addWidget(self.doubleSpinBox_4, 10, 4, 1, 5)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setProperty("value", 0.25)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_2.addWidget(self.doubleSpinBox, 2, 4, 1, 5)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 11, 3, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_3.setMaximum(99999999999999.0)
        self.doubleSpinBox_3.setProperty("value", 100.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_2.addWidget(self.doubleSpinBox_3, 11, 4, 1, 5)
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 2, 0, 1, 1)
        self.comboBox_17 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_17.sizePolicy().hasHeightForWidth())
        self.comboBox_17.setSizePolicy(sizePolicy)
        self.comboBox_17.setMinimumSize(QtCore.QSize(114, 26))
        self.comboBox_17.setMaximumSize(QtCore.QSize(16777215, 26))
        self.comboBox_17.setStyleSheet("")
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_17, 6, 1, 1, 2)
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 7, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 6, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 3, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_3.setMaximum(93)
        self.spinBox_3.setSingleStep(1)
        self.spinBox_3.setProperty("value", 30)
        self.spinBox_3.setDisplayIntegerBase(10)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_2.addWidget(self.spinBox_3, 7, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 10, 3, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_4.setMaximum(93)
        self.spinBox_4.setSingleStep(1)
        self.spinBox_4.setProperty("value", 20)
        self.spinBox_4.setDisplayIntegerBase(10)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_2.addWidget(self.spinBox_4, 7, 4, 1, 5)
        self.label_34 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 11, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 5, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 3, 0, 1, 1)
        self.comboBox_11 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_11.sizePolicy().hasHeightForWidth())
        self.comboBox_11.setSizePolicy(sizePolicy)
        self.comboBox_11.setMinimumSize(QtCore.QSize(114, 26))
        self.comboBox_11.setMaximumSize(QtCore.QSize(16777215, 26))
        self.comboBox_11.setStyleSheet("")
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_11, 3, 1, 1, 2)
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 8, 0, 1, 1)
        self.comboBox_15 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_15.sizePolicy().hasHeightForWidth())
        self.comboBox_15.setSizePolicy(sizePolicy)
        self.comboBox_15.setMinimumSize(QtCore.QSize(114, 26))
        self.comboBox_15.setMaximumSize(QtCore.QSize(16777215, 26))
        self.comboBox_15.setStyleSheet("")
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_15, 8, 1, 1, 8)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(ASTRAL)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = ArrowPushButton(self.groupBox_3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/picture/resourses/if_start_60207.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/picture/resourses/if_Delete_1493279.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(ASTRAL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/picture/resourses/Eye_Care_Services-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon4)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_2.addWidget(self.pushButton_9)
        self.verticalLayout_3.addWidget(self.groupBox)

        self.retranslateUi(ASTRAL)
        self.radioButton_2.toggled['bool'].connect(self.comboBox_20.setEnabled)
        self.radioButton.toggled['bool'].connect(self.comboBox_19.setEnabled)
        self.radioButton_3.toggled['bool'].connect(self.comboBox_18.setEnabled)
        self.radioButton_2.toggled['bool'].connect(self.pushButton_3.setEnabled)
        self.radioButton.toggled['bool'].connect(self.pushButton_8.setEnabled)
        self.radioButton_3.toggled['bool'].connect(self.pushButton_7.setEnabled)
        self.radioButton_2.toggled['bool'].connect(self.toolButton_3.setEnabled)
        self.radioButton.toggled['bool'].connect(self.toolButton_2.setEnabled)
        self.radioButton_3.toggled['bool'].connect(self.toolButton.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ASTRAL)
        ASTRAL.setTabOrder(self.pushButton_3, self.pushButton_9)

    def retranslateUi(self, ASTRAL):
        _translate = QtCore.QCoreApplication.translate
        ASTRAL.setWindowTitle(_translate("ASTRAL", "ASTRAL"))
        self.groupBox_4.setTitle(_translate("ASTRAL", "Input"))
        self.radioButton_3.setText(_translate("ASTRAL", "Raw seq./reads"))
        self.toolButton.setToolTip(_translate("ASTRAL", "Create mapping table"))
        self.toolButton.setText(_translate("ASTRAL", "..."))
        self.radioButton.setText(_translate("ASTRAL", "Alignments"))
        self.toolButton_2.setToolTip(_translate("ASTRAL", "Create mapping table"))
        self.toolButton_2.setText(_translate("ASTRAL", "..."))
        self.radioButton_2.setText(_translate("ASTRAL", "Gene trees:"))
        self.toolButton_3.setToolTip(_translate("ASTRAL", "Create mapping table"))
        self.toolButton_3.setText(_translate("ASTRAL", "..."))
        self.label_8.setToolTip(_translate("ASTRAL", "Sequence file (fasta) containing less reliable nucleotide sequences (e.g. pseudogenes). OPTIONAL!"))
        self.label_8.setText(_translate("ASTRAL", "Constraint:"))
        self.lineEdit_2.setPlaceholderText(_translate("ASTRAL", "Optional! Newick file containing a binary species tree as constraint tree"))
        self.label_9.setToolTip(_translate("ASTRAL", "Sequence file (fasta) containing less reliable nucleotide sequences (e.g. pseudogenes). OPTIONAL!"))
        self.label_9.setText(_translate("ASTRAL", "Guide:"))
        self.lineEdit_3.setPlaceholderText(_translate("ASTRAL", "Optional! Newick file containing binary trees as guide trees"))
        self.label_5.setText(_translate("ASTRAL", "<html><head/><body><p>Click <a href=\"https://github.com/chaoszhang/ASTER\"><span style=\" text-decoration: underline; color:#0000ff;\">here</span></a> to learn more about ASTRAL</p></body></html>"))
        self.label_2.setToolTip(_translate("ASTRAL", "Brief example"))
        self.groupBox_2.setTitle(_translate("ASTRAL", "Parameters"))
        self.comboBox_13.setItemText(0, _translate("ASTRAL", "Hybrid weighting (both branch length and support value)"))
        self.comboBox_13.setItemText(1, _translate("ASTRAL", "Support value only"))
        self.comboBox_13.setItemText(2, _translate("ASTRAL", "Branch length only"))
        self.comboBox_13.setItemText(3, _translate("ASTRAL", "Unweighted"))
        self.lineEdit.setText(_translate("ASTRAL", "ASTRAL.nwk"))
        self.comboBox_16.setItemText(0, _translate("ASTRAL", "1: RY only"))
        self.comboBox_16.setItemText(1, _translate("ASTRAL", "2: RY+WS+KM"))
        self.comboBox_16.setItemText(2, _translate("ASTRAL", "3: auto-select"))
        self.label_29.setText(_translate("ASTRAL", "Chunk:"))
        self.spinBox.setSuffix(_translate("ASTRAL", " (chunk size of each local region)"))
        self.comboBox_12.setItemText(0, _translate("ASTRAL", "Bootstrap support value"))
        self.comboBox_12.setItemText(1, _translate("ASTRAL", "Likelihood (alrt) support value"))
        self.comboBox_12.setItemText(2, _translate("ASTRAL", "Probability (abayes) support value"))
        self.comboBox_12.setItemText(3, _translate("ASTRAL", "Manual (Customize using \"Min/Max/Default support\" options)"))
        self.comboBox_14.setItemText(0, _translate("ASTRAL", "SULength: substitution-per-site unit"))
        self.comboBox_14.setItemText(1, _translate("ASTRAL", "CULength: coalescent unit"))
        self.label_25.setText(_translate("ASTRAL", "Support type:"))
        self.label_26.setText(_translate("ASTRAL", "Weighted mode:"))
        self.comboBox_10.setItemText(0, _translate("ASTRAL", "Default (r=4, s=4)"))
        self.comboBox_10.setItemText(1, _translate("ASTRAL", "Large (r=16, s=16)"))
        self.comboBox_10.setItemText(2, _translate("ASTRAL", "Minimum (r=1, s=0)"))
        self.spinBox_2.setSuffix(_translate("ASTRAL", " (distance for pairing sites)"))
        self.label_33.setText(_translate("ASTRAL", "qcn:"))
        self.comboBox_9.setItemText(0, _translate("ASTRAL", "ASTRAL"))
        self.comboBox_9.setItemText(1, _translate("ASTRAL", "ASTRAL-PRO (for both paralogs and othorlogs)"))
        self.comboBox_9.setItemText(2, _translate("ASTRAL", "Weighted ASTRAL (branch length | support value | both | unweighted)"))
        self.comboBox_9.setItemText(3, _translate("ASTRAL", "Caster-site (Coalescence-aware Alignment-based Species Tree EstimatoR - Site)"))
        self.comboBox_9.setItemText(4, _translate("ASTRAL", "Caster-pair (Coalescence-aware Alignment-based Species Tree EstimatoR - Pair)"))
        self.comboBox_9.setItemText(5, _translate("ASTRAL", "Waster (Without-Alignment/Assembly Species Tree EstimatoR)"))
        self.comboBox_9.setItemText(6, _translate("ASTRAL", "Waster with branch (Without-Alignment/Assembly Species Tree EstimatoR) SLOW"))
        self.label_27.setText(_translate("ASTRAL", "Length unit:"))
        self.doubleSpinBox.setToolTip(_translate("ASTRAL", "Proportion of taxa in the subsample in naive algorithm"))
        self.label_11.setText(_translate("ASTRAL", "Max support:"))
        self.label_23.setText(_translate("ASTRAL", "Search:"))
        self.comboBox_17.setItemText(0, _translate("ASTRAL", "1: run the whole inference"))
        self.comboBox_17.setItemText(1, _translate("ASTRAL", "2: only generate frequent patterns"))
        self.comboBox_17.setItemText(2, _translate("ASTRAL", "3: only generate SNPs"))
        self.comboBox_17.setItemText(3, _translate("ASTRAL", "4: start from SNPs"))
        self.label_32.setText(_translate("ASTRAL", "qcs:"))
        self.label_31.setText(_translate("ASTRAL", "Objective"))
        self.label_3.setToolTip(_translate("ASTRAL", "Proportion of taxa in the subsample in naive algorithm"))
        self.label_3.setText(_translate("ASTRAL", "Proportion:"))
        self.spinBox_3.setSuffix(_translate("ASTRAL", " (Quality control threshold for the SNP)"))
        self.label_6.setText(_translate("ASTRAL", "Threads:"))
        self.label_12.setText(_translate("ASTRAL", "Default support:"))
        self.spinBox_4.setSuffix(_translate("ASTRAL", " (Quality control threshold for non-SNP)"))
        self.label_34.setText(_translate("ASTRAL", "Waster mode:"))
        self.label_7.setText(_translate("ASTRAL", "Min support:"))
        self.label_22.setText(_translate("ASTRAL", "Program:"))
        self.label_30.setText(_translate("ASTRAL", "Pairdist:"))
        self.label.setText(_translate("ASTRAL", "Results name:"))
        self.label_24.setText(_translate("ASTRAL", "Branch values:"))
        self.comboBox_11.setCurrentText(_translate("ASTRAL", "no branch or support"))
        self.comboBox_11.setItemText(0, _translate("ASTRAL", "no branch or support"))
        self.comboBox_11.setItemText(1, _translate("ASTRAL", "length and support only"))
        self.comboBox_11.setItemText(2, _translate("ASTRAL", "detailed"))
        self.comboBox_11.setItemText(3, _translate("ASTRAL", "freqQuad.csv"))
        self.label_28.setText(_translate("ASTRAL", "Ambiguity:"))
        self.comboBox_15.setItemText(0, _translate("ASTRAL", "0: ambiguity codes are treated as N"))
        self.comboBox_15.setItemText(1, _translate("ASTRAL", "1: ambiguity codes are treated as diploid unphased sites"))
        self.groupBox_3.setTitle(_translate("ASTRAL", "Run"))
        self.pushButton.setText(_translate("ASTRAL", "Start"))
        self.pushButton_2.setText(_translate("ASTRAL", "Stop"))
        self.groupBox.setTitle(_translate("ASTRAL", "Progress"))
        self.pushButton_9.setText(_translate("ASTRAL", "Show log"))

from src.CustomWidget import ArrowPushButton, ClickedLableGif, InputQLineEdit, ListQCombobox
from uifiles import myRes_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ASTRAL = QtWidgets.QDialog()
    ui = Ui_ASTRAL()
    ui.setupUi(ASTRAL)
    ASTRAL.show()
    sys.exit(app.exec_())

