# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\HUAWEI\works\phylosuite\PhyloSuite_gitee\PhyloSuite\uifiles\DNA_view.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DNAview(object):
    def setupUi(self, DNAview):
        DNAview.setObjectName("DNAview")
        DNAview.resize(1000, 623)
        DNAview.setMinimumSize(QtCore.QSize(1000, 10))
        self.centralwidget = QtWidgets.QWidget(DNAview)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableWidget.setDragEnabled(True)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.tableWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_3.addWidget(self.tableWidget)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/resourses/table_row_add_after.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/picture/resourses/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon1)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_3.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.tab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/picture/resourses/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon2)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_3.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.tab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/picture/resourses/Custom-Icon-Design-Flatastic-1-Down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon3)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_3.addWidget(self.pushButton_13)
        spacerItem = QtWidgets.QSpacerItem(20, 267, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listWidget = QtWidgets.QListWidget(self.tab_2)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_5.addWidget(self.listWidget)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        self.comboBox_6.setMinimumSize(QtCore.QSize(114, 26))
        self.comboBox_6.setMaximumSize(QtCore.QSize(16777215, 26))
        self.comboBox_6.setStyleSheet("")
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout.addWidget(self.comboBox_6, 0, 1, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.tab_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/picture/resourses/cog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon4)
        self.toolButton_3.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_3.setAutoRaise(True)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout.addWidget(self.toolButton_3, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 0, 1, 1)
        self.lineEdit = ComLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox.setMaximum(99999999999.0)
        self.doubleSpinBox.setProperty("value", 25.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox.setMaximum(99999999)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_2.setMaximum(99999999)
        self.spinBox_2.setProperty("value", 1)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_3.setMaximum(99999999)
        self.spinBox_3.setProperty("value", 2)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout.addWidget(self.spinBox_3, 5, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_4.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_4.addWidget(self.checkBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout_2.addWidget(self.splitter)
        DNAview.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DNAview)
        self.statusbar.setObjectName("statusbar")
        DNAview.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(DNAview)
        self.toolBar.setIconSize(QtCore.QSize(30, 30))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        DNAview.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionUpdate_figure = QtWidgets.QAction(DNAview)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/picture/resourses/refresh-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpdate_figure.setIcon(icon5)
        self.actionUpdate_figure.setObjectName("actionUpdate_figure")
        self.actionFit_The_Window = QtWidgets.QAction(DNAview)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/seq_Viewer/resourses/seq_viewer/28105126-d6a6ce90-66fb-11e7-8546-72517772000b.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFit_The_Window.setIcon(icon6)
        self.actionFit_The_Window.setObjectName("actionFit_The_Window")
        self.actionPDF = QtWidgets.QAction(DNAview)
        self.actionPDF.setObjectName("actionPDF")
        self.actionJPG = QtWidgets.QAction(DNAview)
        self.actionJPG.setObjectName("actionJPG")
        self.actionsave_as = QtWidgets.QAction(DNAview)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/picture/resourses/Save-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsave_as.setIcon(icon7)
        self.actionsave_as.setObjectName("actionsave_as")
        self.actionsettings = QtWidgets.QAction(DNAview)
        self.actionsettings.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/picture/resourses/settings-icon-flat_343252.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsettings.setIcon(icon8)
        self.actionsettings.setObjectName("actionsettings")
        self.toolBar.addAction(self.actionUpdate_figure)
        self.toolBar.addAction(self.actionsave_as)
        self.toolBar.addAction(self.actionsettings)

        self.retranslateUi(DNAview)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(DNAview)

    def retranslateUi(self, DNAview):
        _translate = QtCore.QCoreApplication.translate
        DNAview.setWindowTitle(_translate("DNAview", "DNA viewer"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DNAview", "Genes/features"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DNAview", "Fill color"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DNAview", "Border color"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DNAview", "Text color"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("DNAview", "Uniform length"))
        self.pushButton_7.setText(_translate("DNAview", "Add row"))
        self.pushButton_11.setText(_translate("DNAview", "Delete row"))
        self.pushButton_12.setText(_translate("DNAview", "Move up"))
        self.pushButton_13.setText(_translate("DNAview", "Move down"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DNAview", "Genes"))
        self.label_6.setText(_translate("DNAview", "<html><head/><body><p>Double-click to edit; Drag and drop to reorder</p></body></html>"))
        self.label.setText(_translate("DNAview", "Settings"))
        self.comboBox_6.setToolTip(_translate("DNAview", "select or edit the type of sequence and features you wish to extract"))
        self.toolButton_3.setToolTip(_translate("DNAview", "edit extract settings"))
        self.toolButton_3.setText(_translate("DNAview", "..."))
        self.label_13.setText(_translate("DNAview", "Font:"))
        self.lineEdit.setText(_translate("DNAview", "Arial"))
        self.label_2.setText(_translate("DNAview", "Feature height:"))
        self.label_3.setText(_translate("DNAview", "Feature level:"))
        self.label_4.setText(_translate("DNAview", "Annotation level:"))
        self.label_5.setText(_translate("DNAview", "Right spae of label:"))
        self.checkBox.setText(_translate("DNAview", "Plot tick and labels"))
        self.checkBox_2.setText(_translate("DNAview", "Use uniform length"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DNAview", "options"))
        self.toolBar.setWindowTitle(_translate("DNAview", "toolBar"))
        self.actionUpdate_figure.setText(_translate("DNAview", "Update figure"))
        self.actionUpdate_figure.setToolTip(_translate("DNAview", "Update figure"))
        self.actionFit_The_Window.setText(_translate("DNAview", "Fit The Window"))
        self.actionPDF.setText(_translate("DNAview", "PDF"))
        self.actionJPG.setText(_translate("DNAview", "JPG"))
        self.actionsave_as.setText(_translate("DNAview", "save as"))
        self.actionsettings.setText(_translate("DNAview", "settings"))
        self.actionsettings.setToolTip(_translate("DNAview", "Show/Hide settings"))

from src.CustomWidget import ComLineEdit
from uifiles import myRes_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DNAview = QtWidgets.QMainWindow()
    ui = Ui_DNAview()
    ui.setupUi(DNAview)
    DNAview.show()
    sys.exit(app.exec_())

