# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\F\Work\python\bioinfo_excercise\PhyloSuite\codes\PhyloSuite\uifiles\gbEditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GBeditor(object):
    def setupUi(self, GBeditor):
        GBeditor.setObjectName("GBeditor")
        GBeditor.resize(720, 651)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GBeditor.sizePolicy().hasHeightForWidth())
        GBeditor.setSizePolicy(sizePolicy)
        GBeditor.setSizeGripEnabled(True)
        self.gridLayout_3 = QtWidgets.QGridLayout(GBeditor)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setSpacing(3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(GBeditor)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tableWidget = QtWidgets.QTableWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 85))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 85))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.plainTextEdit_gb = QtWidgets.QPlainTextEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.plainTextEdit_gb.setFont(font)
        self.plainTextEdit_gb.setAutoFillBackground(True)
        self.plainTextEdit_gb.setObjectName("plainTextEdit_gb")
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(GBeditor)
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.spinBox = QtWidgets.QSpinBox(GBeditor)
        self.spinBox.setEnabled(False)
        self.spinBox.setMinimumSize(QtCore.QSize(0, 24))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(10000)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(GBeditor)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/resourses/valid_shield-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(GBeditor)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/picture/resourses/Spotlight_OS_X.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(GBeditor)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/picture/resourses/original.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 2, 1)
        self.pushButton_rmv = QtWidgets.QPushButton(GBeditor)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/picture/resourses/if_Delete_1493279.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_rmv.setIcon(icon3)
        self.pushButton_rmv.setObjectName("pushButton_rmv")
        self.gridLayout_2.addWidget(self.pushButton_rmv, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)

        self.retranslateUi(GBeditor)
        self.checkBox.toggled['bool'].connect(self.spinBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(GBeditor)

    def retranslateUi(self, GBeditor):
        _translate = QtCore.QCoreApplication.translate
        GBeditor.setWindowTitle(_translate("GBeditor", "GenBank Editor"))
        self.checkBox.setText(_translate("GBeditor", "Set NCR threshold (intergenic region > ? bp):"))
        self.pushButton_2.setText(_translate("GBeditor", "Validate"))
        self.pushButton.setText(_translate("GBeditor", "Find"))
        self.pushButton_7.setToolTip(_translate("GBeditor", "Predict unrecognized tRNAs using ARWEN"))
        self.pushButton_7.setText(_translate("GBeditor", "Predict tRNA (LEU and SER)"))
        self.pushButton_rmv.setText(_translate("GBeditor", "Remove all IDs with no annotation"))
from uifiles import myRes_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GBeditor = QtWidgets.QDialog()
    ui = Ui_GBeditor()
    ui.setupUi(GBeditor)
    GBeditor.show()
    sys.exit(app.exec_())
