# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\works\ZD\phylosuite\uifiles\mafft.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mafft(object):
    def setupUi(self, mafft):
        mafft.setObjectName("mafft")
        mafft.resize(622, 578)
        mafft.setStyleSheet("")
        mafft.setSizeGripEnabled(True)
        self.gridLayout_5 = QtWidgets.QGridLayout(mafft)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(mafft)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton = ArrowPushButton(self.groupBox_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/resourses/if_start_60207.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/picture/resourses/if_Delete_1493279.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(mafft)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.comboBox_4 = ListQCombobox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setAcceptDrops(True)
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_4.addWidget(self.comboBox_4, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.label_7 = ClickedLableGif(self.groupBox_4)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 1, 0, 1, 3)
        self.gridLayout_5.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(mafft)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.normal_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.normal_radioButton.setEnabled(True)
        self.normal_radioButton.setChecked(False)
        self.normal_radioButton.setObjectName("normal_radioButton")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(mafft)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.normal_radioButton)
        self.horizontalLayout.addWidget(self.normal_radioButton)
        self.codon_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.codon_radioButton.setChecked(True)
        self.codon_radioButton.setObjectName("codon_radioButton")
        self.buttonGroup_2.addButton(self.codon_radioButton)
        self.horizontalLayout.addWidget(self.codon_radioButton)
        self.N2P_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.N2P_radioButton.setObjectName("N2P_radioButton")
        self.buttonGroup_2.addButton(self.N2P_radioButton)
        self.horizontalLayout.addWidget(self.N2P_radioButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.AA_radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.AA_radioButton_2.setChecked(False)
        self.AA_radioButton_2.setObjectName("AA_radioButton_2")
        self.buttonGroup = QtWidgets.QButtonGroup(mafft)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.AA_radioButton_2)
        self.horizontalLayout_2.addWidget(self.AA_radioButton_2)
        self.PCG_radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.PCG_radioButton_2.setChecked(True)
        self.PCG_radioButton_2.setObjectName("PCG_radioButton_2")
        self.buttonGroup.addButton(self.PCG_radioButton_2)
        self.horizontalLayout_2.addWidget(self.PCG_radioButton_2)
        self.RNAs_radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.RNAs_radioButton_2.setObjectName("RNAs_radioButton_2")
        self.buttonGroup.addButton(self.RNAs_radioButton_2)
        self.horizontalLayout_2.addWidget(self.RNAs_radioButton_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 2)
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 3, 0, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_9.sizePolicy().hasHeightForWidth())
        self.comboBox_9.setSizePolicy(sizePolicy)
        self.comboBox_9.setMinimumSize(QtCore.QSize(114, 26))
        self.comboBox_9.setMaximumSize(QtCore.QSize(16777215, 26))
        self.comboBox_9.setStyleSheet("")
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_9, 3, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 4, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setMinimumSize(QtCore.QSize(13, 26))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_3, 4, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 5, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMinimumSize(QtCore.QSize(13, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 5, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 6, 0, 1, 1)
        self.pushButton_par = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_par.sizePolicy().hasHeightForWidth())
        self.pushButton_par.setSizePolicy(sizePolicy)
        self.pushButton_par.setMinimumSize(QtCore.QSize(0, 26))
        self.pushButton_par.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/picture/resourses/keynote.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_par.setIcon(icon2)
        self.pushButton_par.setObjectName("pushButton_par")
        self.gridLayout_2.addWidget(self.pushButton_par, 6, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(mafft)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout.addWidget(self.progressBar_2, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/picture/resourses/Eye_Care_Services-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon3)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 3, 0, 1, 1)
        self.label.setBuddy(self.normal_radioButton)
        self.label_24.setBuddy(self.comboBox_3)
        self.label_23.setBuddy(self.comboBox_2)
        self.label_25.setBuddy(self.comboBox_2)

        self.retranslateUi(mafft)
        self.AA_radioButton_2.toggled['bool'].connect(self.normal_radioButton.setEnabled)
        self.RNAs_radioButton_2.toggled['bool'].connect(self.normal_radioButton.setEnabled)
        self.AA_radioButton_2.toggled['bool'].connect(self.codon_radioButton.setDisabled)
        self.AA_radioButton_2.toggled['bool'].connect(self.N2P_radioButton.setDisabled)
        self.RNAs_radioButton_2.toggled['bool'].connect(self.N2P_radioButton.setDisabled)
        self.RNAs_radioButton_2.toggled['bool'].connect(self.codon_radioButton.setDisabled)
        self.PCG_radioButton_2.toggled['bool'].connect(self.normal_radioButton.setDisabled)
        self.PCG_radioButton_2.toggled['bool'].connect(self.codon_radioButton.setEnabled)
        self.PCG_radioButton_2.toggled['bool'].connect(self.N2P_radioButton.setEnabled)
        self.PCG_radioButton_2.toggled['bool'].connect(self.codon_radioButton.toggle)
        self.RNAs_radioButton_2.toggled['bool'].connect(self.normal_radioButton.toggle)
        self.AA_radioButton_2.toggled['bool'].connect(self.normal_radioButton.toggle)
        self.checkBox_2.toggled['bool'].connect(self.AA_radioButton_2.setEnabled)
        self.checkBox_2.toggled['bool'].connect(self.PCG_radioButton_2.setEnabled)
        self.checkBox_2.toggled['bool'].connect(self.RNAs_radioButton_2.setEnabled)
        self.normal_radioButton.toggled['bool'].connect(self.comboBox_9.setDisabled)
        self.N2P_radioButton.toggled['bool'].connect(self.comboBox_9.setDisabled)
        self.codon_radioButton.toggled['bool'].connect(self.comboBox_9.setEnabled)
        self.N2P_radioButton.toggled['bool'].connect(self.comboBox_9.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(mafft)
        mafft.setTabOrder(self.pushButton_3, self.checkBox_2)
        mafft.setTabOrder(self.checkBox_2, self.comboBox_3)
        mafft.setTabOrder(self.comboBox_3, self.comboBox_4)
        mafft.setTabOrder(self.comboBox_4, self.comboBox_2)
        mafft.setTabOrder(self.comboBox_2, self.pushButton_par)
        mafft.setTabOrder(self.pushButton_par, self.comboBox_9)
        mafft.setTabOrder(self.comboBox_9, self.pushButton)
        mafft.setTabOrder(self.pushButton, self.pushButton_2)
        mafft.setTabOrder(self.pushButton_2, self.pushButton_9)
        mafft.setTabOrder(self.pushButton_9, self.normal_radioButton)
        mafft.setTabOrder(self.normal_radioButton, self.codon_radioButton)
        mafft.setTabOrder(self.codon_radioButton, self.N2P_radioButton)
        mafft.setTabOrder(self.N2P_radioButton, self.AA_radioButton_2)
        mafft.setTabOrder(self.AA_radioButton_2, self.PCG_radioButton_2)
        mafft.setTabOrder(self.PCG_radioButton_2, self.RNAs_radioButton_2)

    def retranslateUi(self, mafft):
        _translate = QtCore.QCoreApplication.translate
        mafft.setWindowTitle(_translate("mafft", "MAFFT"))
        self.groupBox_3.setTitle(_translate("mafft", "Run"))
        self.pushButton.setText(_translate("mafft", "Start"))
        self.pushButton_2.setText(_translate("mafft", "Stop"))
        self.groupBox_4.setTitle(_translate("mafft", "Input"))
        self.label_4.setText(_translate("mafft", "Input:"))
        self.label_5.setText(_translate("mafft", "<html><head/><body><p>Try to drag your <span style=\" font-weight:600; color:#ff0000;\">fasta</span> file and drop here if you want to use custom files</p></body></html>"))
        self.label_8.setText(_translate("mafft", "Demo:"))
        self.label_7.setToolTip(_translate("mafft", "Brief example"))
        self.groupBox_2.setTitle(_translate("mafft", "Parameter"))
        self.label.setText(_translate("mafft", "Alignment Mode:"))
        self.normal_radioButton.setText(_translate("mafft", "Normal"))
        self.codon_radioButton.setText(_translate("mafft", "Codon"))
        self.N2P_radioButton.setText(_translate("mafft", "N2P"))
        self.checkBox_2.setText(_translate("mafft", "Extracted-Seq.:"))
        self.AA_radioButton_2.setToolTip(_translate("mafft", "Amino acid sequences"))
        self.AA_radioButton_2.setText(_translate("mafft", "AA"))
        self.PCG_radioButton_2.setToolTip(_translate("mafft", "Protein-coding genes"))
        self.PCG_radioButton_2.setText(_translate("mafft", "PCGs"))
        self.RNAs_radioButton_2.setToolTip(_translate("mafft", "RNA sequences (rRNA and tRNA)"))
        self.RNAs_radioButton_2.setText(_translate("mafft", "RNAs"))
        self.label_9.setText(_translate("mafft", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">Note</span>: The above three options are only used to auto-input files! </p></body></html>"))
        self.label_22.setText(_translate("mafft", "Code Table:"))
        self.comboBox_9.setItemText(0, _translate("mafft", "1 The standard code"))
        self.comboBox_9.setItemText(1, _translate("mafft", "2 Vertebrate mitochondrial code"))
        self.comboBox_9.setItemText(2, _translate("mafft", "3 The Yeast Mitochondrial Code"))
        self.comboBox_9.setItemText(3, _translate("mafft", "4 Mold, Protozoan, and Coelenterate Mitochondrial code and Mycoplasma/Spiroplasma code"))
        self.comboBox_9.setItemText(4, _translate("mafft", "5 Invertebrate mitochondrial"))
        self.comboBox_9.setItemText(5, _translate("mafft", "6 The Ciliate, Dasycladacean and Hexamita Nuclear Code"))
        self.comboBox_9.setItemText(6, _translate("mafft", "9 Echinoderm and Flatworm mitochondrial code"))
        self.comboBox_9.setItemText(7, _translate("mafft", "10 The Euplotid Nuclear Code"))
        self.comboBox_9.setItemText(8, _translate("mafft", "11 The Bacterial, Archaeal and Plant Plastid Code"))
        self.comboBox_9.setItemText(9, _translate("mafft", "12 The Alternative Yeast Nuclear Code"))
        self.comboBox_9.setItemText(10, _translate("mafft", "13 Ascidian mitochondrial code"))
        self.comboBox_9.setItemText(11, _translate("mafft", "14 Alternative flatworm mitochondrial code"))
        self.comboBox_9.setItemText(12, _translate("mafft", "16 Chlorophycean Mitochondrial Code"))
        self.comboBox_9.setItemText(13, _translate("mafft", "21 Trematode Mitochondrial Code"))
        self.comboBox_9.setItemText(14, _translate("mafft", "22 Scenedesmus obliquus Mitochondrial Code"))
        self.comboBox_9.setItemText(15, _translate("mafft", "23 Thraustochytrium Mitochondrial Code"))
        self.comboBox_9.setItemText(16, _translate("mafft", "24 Pterobranchia Mitochondrial Code"))
        self.comboBox_9.setItemText(17, _translate("mafft", "25 Candidate Division SR1 and Gracilibacteria Code"))
        self.comboBox_9.setItemText(18, _translate("mafft", "26 Pachysolen tannophilus Nuclear Code"))
        self.comboBox_9.setItemText(19, _translate("mafft", "27 Karyorelict Nuclear"))
        self.comboBox_9.setItemText(20, _translate("mafft", "28 Condylostoma Nuclear"))
        self.comboBox_9.setItemText(21, _translate("mafft", "29 Mesodinium Nuclear"))
        self.comboBox_9.setItemText(22, _translate("mafft", "30 Peritrich Nuclear"))
        self.comboBox_9.setItemText(23, _translate("mafft", "31 Blastocrithidia Nuclear"))
        self.label_24.setText(_translate("mafft", "Strategy:"))
        self.comboBox_3.setItemText(0, _translate("mafft", "1. --auto"))
        self.comboBox_3.setItemText(1, _translate("mafft", "2. FFT-NS-1 (fast)"))
        self.comboBox_3.setItemText(2, _translate("mafft", "3. FFT-NS-2 (default)"))
        self.comboBox_3.setItemText(3, _translate("mafft", "4. G-INS-i  (accurate)"))
        self.comboBox_3.setItemText(4, _translate("mafft", "5. L-INS-i  (accurate)"))
        self.comboBox_3.setItemText(5, _translate("mafft", "6. E-INS-i  (accurate)"))
        self.label_23.setText(_translate("mafft", "Export Format:"))
        self.comboBox_2.setItemText(0, _translate("mafft", "1. CLUSTAL Format / Sorted"))
        self.comboBox_2.setItemText(1, _translate("mafft", "2. CLUSTAL Format / Input order"))
        self.comboBox_2.setItemText(2, _translate("mafft", "3. FASTA Format   / Sorted"))
        self.comboBox_2.setItemText(3, _translate("mafft", "4. FASTA Format   / Input order"))
        self.comboBox_2.setItemText(4, _translate("mafft", "5. PHYLIP Format  / Sorted"))
        self.comboBox_2.setItemText(5, _translate("mafft", "6. PHYLIP Format  / Input order"))
        self.label_25.setText(_translate("mafft", "Parameters:"))
        self.pushButton_par.setText(_translate("mafft", "Additional Parameters"))
        self.groupBox.setTitle(_translate("mafft", "Progress"))
        self.label_3.setText(_translate("mafft", "file:"))
        self.label_2.setText(_translate("mafft", "Total:"))
        self.label_6.setText(_translate("mafft", "Log:"))
        self.pushButton_9.setText(_translate("mafft", "Show log"))

from src.CustomWidget import ArrowPushButton, ClickedLableGif, ListQCombobox
from uifiles import myRes_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mafft = QtWidgets.QDialog()
    ui = Ui_mafft()
    ui.setupUi(mafft)
    mafft.show()
    sys.exit(app.exec_())

