# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\F\Work\python\bioinfo_excercise\PhyloSuite\codes\PhyloSuite_gitee\PhyloSuite\uifiles\mcmctree.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MCMCTreeGUI(object):
    def setupUi(self, MCMCTreeGUI):
        MCMCTreeGUI.setObjectName("MCMCTreeGUI")
        MCMCTreeGUI.resize(1310, 740)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(MCMCTreeGUI)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.scrollArea = QtWidgets.QScrollArea(MCMCTreeGUI)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1271, 784))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_2 = InputQLineEdit(self.groupBox)
        self.lineEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.lineEdit = InputQLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_13.setObjectName("checkBox_13")
        self.horizontalLayout.addWidget(self.checkBox_13)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setOpenExternalLinks(True)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_2.addWidget(self.label_23)
        spacerItem = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_2.addWidget(self.label_24)
        self.label_25 = ClickedLableGif(self.groupBox)
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_2.addWidget(self.label_25)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_10.addWidget(self.groupBox)
        self.tabWidgetMCMC = QtWidgets.QTabWidget(self.scrollAreaWidgetContents_2)
        self.tabWidgetMCMC.setObjectName("tabWidgetMCMC")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_3.addWidget(self.comboBox, 5, 2, 1, 3)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_2.setEnabled(False)
        self.doubleSpinBox_2.setProperty("value", 6.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_3.addWidget(self.doubleSpinBox_2, 6, 2, 1, 2)
        self.checkBox_14 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_3.addWidget(self.checkBox_14, 1, 0, 1, 1)
        self.spinBox_18 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_18.setMinimum(1)
        self.spinBox_18.setMaximum(100)
        self.spinBox_18.setSingleStep(1)
        self.spinBox_18.setProperty("value", 5)
        self.spinBox_18.setObjectName("spinBox_18")
        self.gridLayout_3.addWidget(self.spinBox_18, 0, 2, 1, 2)
        self.checkBox_15 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_15.setEnabled(False)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_3.addWidget(self.checkBox_15, 5, 5, 1, 1)
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_10.setProperty("value", 1.0)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.gridLayout_3.addWidget(self.doubleSpinBox_10, 4, 5, 1, 1)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_7.setEnabled(False)
        self.doubleSpinBox_7.setProperty("value", 2.0)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.gridLayout_3.addWidget(self.doubleSpinBox_7, 6, 4, 1, 2)
        self.spinBox_19 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_19.setMinimum(1)
        self.spinBox_19.setMaximum(999999999)
        self.spinBox_19.setSingleStep(10)
        self.spinBox_19.setProperty("value", 10)
        self.spinBox_19.setObjectName("spinBox_19")
        self.gridLayout_3.addWidget(self.spinBox_19, 0, 4, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setEnabled(False)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 6, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_3, 3, 2, 1, 4)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setEnabled(False)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 5, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_4, 2, 2, 1, 4)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox.setEnabled(False)
        self.doubleSpinBox.setMaximum(1000000000000.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_3.addWidget(self.doubleSpinBox, 1, 2, 1, 2)
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 0, 0, 1, 1)
        self.doubleSpinBox_19 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_19.setEnabled(False)
        self.doubleSpinBox_19.setMaximum(1000000000000.0)
        self.doubleSpinBox_19.setObjectName("doubleSpinBox_19")
        self.gridLayout_3.addWidget(self.doubleSpinBox_19, 1, 4, 1, 2)
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 4, 0, 1, 1)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_8.setProperty("value", 2.0)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.gridLayout_3.addWidget(self.doubleSpinBox_8, 4, 2, 1, 1)
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_9.setProperty("value", 20.0)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.gridLayout_3.addWidget(self.doubleSpinBox_9, 4, 3, 1, 2)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setEnabled(False)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 6, 0, 1, 1)
        self.doubleSpinBox_14 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_14.setEnabled(False)
        self.doubleSpinBox_14.setProperty("value", 1.0)
        self.doubleSpinBox_14.setObjectName("doubleSpinBox_14")
        self.gridLayout_4.addWidget(self.doubleSpinBox_14, 6, 1, 1, 4)
        self.comboBox_8 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_8.setObjectName("comboBox_8")
        self.gridLayout_4.addWidget(self.comboBox_8, 3, 1, 1, 4)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 1, 0, 1, 1)
        self.doubleSpinBox_15 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_15.setEnabled(False)
        self.doubleSpinBox_15.setProperty("value", 1.0)
        self.doubleSpinBox_15.setObjectName("doubleSpinBox_15")
        self.gridLayout_4.addWidget(self.doubleSpinBox_15, 6, 5, 1, 2)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_4.setSingleStep(0.1)
        self.doubleSpinBox_4.setProperty("value", 1.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_4.addWidget(self.doubleSpinBox_4, 1, 3, 1, 2)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_5.setSingleStep(0.1)
        self.doubleSpinBox_5.setProperty("value", 0.0)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout_4.addWidget(self.doubleSpinBox_5, 1, 5, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_11.setChecked(True)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_4.addWidget(self.checkBox_11, 3, 5, 1, 2)
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_7, 2, 1, 1, 6)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_3.setSingleStep(0.1)
        self.doubleSpinBox_3.setProperty("value", 1.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_4.addWidget(self.doubleSpinBox_3, 1, 1, 1, 2)
        self.spinBox_20 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_20.setMinimum(1)
        self.spinBox_20.setMaximum(999999999)
        self.spinBox_20.setSingleStep(10000)
        self.spinBox_20.setProperty("value", 20000)
        self.spinBox_20.setDisplayIntegerBase(10)
        self.spinBox_20.setObjectName("spinBox_20")
        self.gridLayout_4.addWidget(self.spinBox_20, 0, 0, 1, 7)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_6.setEnabled(False)
        self.doubleSpinBox_6.setSingleStep(0.1)
        self.doubleSpinBox_6.setProperty("value", 0.5)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout_4.addWidget(self.doubleSpinBox_6, 5, 1, 1, 4)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setEnabled(False)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 5, 0, 1, 1)
        self.spinBox_21 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_21.setEnabled(False)
        self.spinBox_21.setProperty("value", 5)
        self.spinBox_21.setObjectName("spinBox_21")
        self.gridLayout_4.addWidget(self.spinBox_21, 5, 6, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setEnabled(False)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 5, 5, 1, 1)
        self.comboBox_13 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_13, 1, 6, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 4, 0, 1, 1)
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_13.setProperty("value", 1.0)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.gridLayout_4.addWidget(self.doubleSpinBox_13, 4, 6, 1, 1)
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_12.setProperty("value", 10.0)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.gridLayout_4.addWidget(self.doubleSpinBox_12, 4, 3, 1, 3)
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_11.setProperty("value", 1.0)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.gridLayout_4.addWidget(self.doubleSpinBox_11, 4, 1, 1, 2)
        self.horizontalLayout_3.addLayout(self.gridLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_4.addWidget(self.label_27)
        self.comboBox_14 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_14.sizePolicy().hasHeightForWidth())
        self.comboBox_14.setSizePolicy(sizePolicy)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_14)
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_12.setObjectName("checkBox_12")
        self.horizontalLayout_4.addWidget(self.checkBox_12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_10.addWidget(self.pushButton_8, 0, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_10.addWidget(self.pushButton_7, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_10)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_continue = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_continue.sizePolicy().hasHeightForWidth())
        self.pushButton_continue.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/resourses/Play-pause_button_play_stop_blue_pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_continue.setIcon(icon)
        self.pushButton_continue.setObjectName("pushButton_continue")
        self.horizontalLayout_11.addWidget(self.pushButton_continue)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/picture/resourses/Menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_11.addWidget(self.pushButton_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.tabWidgetMCMC.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.line = QtWidgets.QFrame(self.groupBox_5)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_6.addWidget(self.line)
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_6)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_6.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_6.addWidget(self.checkBox_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_8.addWidget(self.label_32)
        self.line_3 = QtWidgets.QFrame(self.groupBox_5)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_8.addWidget(self.line_3)
        self.label_33 = QtWidgets.QLabel(self.groupBox_5)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_8.addWidget(self.label_33)
        self.comboBox_9 = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_9.sizePolicy().hasHeightForWidth())
        self.comboBox_9.setSizePolicy(sizePolicy)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_9)
        self.label_34 = QtWidgets.QLabel(self.groupBox_5)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_8.addWidget(self.label_34)
        self.comboBox_11 = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_11.sizePolicy().hasHeightForWidth())
        self.comboBox_11.setSizePolicy(sizePolicy)
        self.comboBox_11.setObjectName("comboBox_11")
        self.horizontalLayout_8.addWidget(self.comboBox_11)
        self.label_35 = QtWidgets.QLabel(self.groupBox_5)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_8.addWidget(self.label_35)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_2.sizePolicy().hasHeightForWidth())
        self.spinBox_2.setSizePolicy(sizePolicy)
        self.spinBox_2.setMaximum(999999999)
        self.spinBox_2.setProperty("value", 6)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_8.addWidget(self.spinBox_2)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_8.addWidget(self.checkBox_6)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_8.addWidget(self.checkBox_5)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_8.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout_8.addWidget(self.checkBox_8)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_36 = QtWidgets.QLabel(self.groupBox_5)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_9.addWidget(self.label_36)
        self.line_4 = QtWidgets.QFrame(self.groupBox_5)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_9.addWidget(self.line_4)
        self.label_37 = QtWidgets.QLabel(self.groupBox_5)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_9.addWidget(self.label_37)
        self.comboBox_12 = QtWidgets.QComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_12.sizePolicy().hasHeightForWidth())
        self.comboBox_12.setSizePolicy(sizePolicy)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_12)
        self.label_38 = QtWidgets.QLabel(self.groupBox_5)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_9.addWidget(self.label_38)
        self.doubleSpinBox_16 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_16.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_16.setSizePolicy(sizePolicy)
        self.doubleSpinBox_16.setMaximum(99999999999999.0)
        self.doubleSpinBox_16.setProperty("value", 1.0)
        self.doubleSpinBox_16.setObjectName("doubleSpinBox_16")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_16)
        self.label_39 = QtWidgets.QLabel(self.groupBox_5)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_9.addWidget(self.label_39)
        self.doubleSpinBox_17 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_17.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_17.setSizePolicy(sizePolicy)
        self.doubleSpinBox_17.setMaximum(99999999999999.0)
        self.doubleSpinBox_17.setProperty("value", 1.0)
        self.doubleSpinBox_17.setObjectName("doubleSpinBox_17")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_17)
        self.label_40 = QtWidgets.QLabel(self.groupBox_5)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_9.addWidget(self.label_40)
        self.doubleSpinBox_18 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_18.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_18.setSizePolicy(sizePolicy)
        self.doubleSpinBox_18.setMaximum(99999999999999.0)
        self.doubleSpinBox_18.setProperty("value", 1.0)
        self.doubleSpinBox_18.setObjectName("doubleSpinBox_18")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_18)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_7.addWidget(self.label_29)
        self.line_2 = QtWidgets.QFrame(self.groupBox_5)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_7.addWidget(self.line_2)
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_7.addWidget(self.label_30)
        self.comboBox_10 = CheckableComboBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_10.sizePolicy().hasHeightForWidth())
        self.comboBox_10.setSizePolicy(sizePolicy)
        self.comboBox_10.setMinimumSize(QtCore.QSize(95, 26))
        self.comboBox_10.setObjectName("comboBox_10")
        self.horizontalLayout_7.addWidget(self.comboBox_10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout_5.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout_5.addWidget(self.checkBox_10)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_3.setToolTip("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_5.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_4.setToolTip("")
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_5.addWidget(self.checkBox_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_10.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_10.addWidget(self.pushButton_13)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.tabWidgetMCMC.addTab(self.tab_2, "")
        self.verticalLayout_10.addWidget(self.tabWidgetMCMC)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_2 = ArrowPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/picture/resourses/if_Delete_1493279.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_5 = ArrowPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_5.setAutoFillBackground(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/picture/resourses/if_start_60207.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setAutoExclusive(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_4)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_12.addWidget(self.progressBar, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_4)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/picture/resourses/Eye_Care_Services-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon4)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_12.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_12)
        self.verticalLayout_10.addWidget(self.groupBox_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_11.addWidget(self.scrollArea)

        self.retranslateUi(MCMCTreeGUI)
        self.tabWidgetMCMC.setCurrentIndex(0)
        self.checkBox_14.toggled['bool'].connect(self.doubleSpinBox.setEnabled)
        self.checkBox_14.toggled['bool'].connect(self.doubleSpinBox_19.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MCMCTreeGUI)
        MCMCTreeGUI.setTabOrder(self.doubleSpinBox, self.doubleSpinBox_6)
        MCMCTreeGUI.setTabOrder(self.doubleSpinBox_6, self.spinBox_21)
        MCMCTreeGUI.setTabOrder(self.spinBox_21, self.doubleSpinBox_3)
        MCMCTreeGUI.setTabOrder(self.doubleSpinBox_3, self.doubleSpinBox_4)
        MCMCTreeGUI.setTabOrder(self.doubleSpinBox_4, self.doubleSpinBox_5)
        MCMCTreeGUI.setTabOrder(self.doubleSpinBox_5, self.spinBox_18)
        MCMCTreeGUI.setTabOrder(self.spinBox_18, self.spinBox_19)
        MCMCTreeGUI.setTabOrder(self.spinBox_19, self.spinBox_20)
        MCMCTreeGUI.setTabOrder(self.spinBox_20, self.pushButton_3)
        MCMCTreeGUI.setTabOrder(self.pushButton_3, self.pushButton_4)
        MCMCTreeGUI.setTabOrder(self.pushButton_4, self.lineEdit)
        MCMCTreeGUI.setTabOrder(self.lineEdit, self.pushButton)

    def retranslateUi(self, MCMCTreeGUI):
        _translate = QtCore.QCoreApplication.translate
        MCMCTreeGUI.setWindowTitle(_translate("MCMCTreeGUI", "MDGUI"))
        self.groupBox.setTitle(_translate("MCMCTreeGUI", "Input"))
        self.label.setText(_translate("MCMCTreeGUI", "Treefile"))
        self.label_4.setText(_translate("MCMCTreeGUI", "Alignment"))
        self.lineEdit_2.setPlaceholderText(_translate("MCMCTreeGUI", "Input alignment with FASTA/NEXUS/PHYLIP/PAML formats"))
        self.lineEdit.setPlaceholderText(_translate("MCMCTreeGUI", "The tree should be NEWICK format "))
        self.label_8.setText(_translate("MCMCTreeGUI", "seqtype"))
        self.comboBox_2.setItemText(0, _translate("MCMCTreeGUI", "nucleotides"))
        self.comboBox_2.setItemText(1, _translate("MCMCTreeGUI", "codons"))
        self.comboBox_2.setItemText(2, _translate("MCMCTreeGUI", "AAs"))
        self.checkBox_13.setText(_translate("MCMCTreeGUI", "Enabling tip-dating analyses"))
        self.pushButton.setText(_translate("MCMCTreeGUI", "Add calibration points in tree"))
        self.label_2.setText(_translate("MCMCTreeGUI", "Species："))
        self.label_23.setText(_translate("MCMCTreeGUI", "<html><head/><body><p>Click <a href=\"http://abacus.gene.ucl.ac.uk/software/paml.html\"><span style=\" text-decoration: underline; color:#0000ff;\">here</span></a> to learn more about <span style=\" font-weight:600; color:#ff0000;\">MCMCTree</span></p></body></html>"))
        self.label_24.setText(_translate("MCMCTreeGUI", "Demo:"))
        self.label_25.setToolTip(_translate("MCMCTreeGUI", "Brief example"))
        self.groupBox_2.setTitle(_translate("MCMCTreeGUI", "MCMCTree.ctl parameters setting"))
        self.checkBox_14.setText(_translate("MCMCTreeGUI", "RootAge"))
        self.spinBox_18.setSuffix(_translate("MCMCTreeGUI", "%"))
        self.spinBox_18.setPrefix(_translate("MCMCTreeGUI", "burin: "))
        self.checkBox_15.setText(_translate("MCMCTreeGUI", "cleandata"))
        self.spinBox_19.setPrefix(_translate("MCMCTreeGUI", "sampfreq: "))
        self.label_18.setText(_translate("MCMCTreeGUI", "kappa_gamma"))
        self.label_9.setText(_translate("MCMCTreeGUI", "usedata"))
        self.comboBox_3.setCurrentText(_translate("MCMCTreeGUI", "no data (prior)"))
        self.comboBox_3.setItemText(0, _translate("MCMCTreeGUI", "no data (prior)"))
        self.comboBox_3.setItemText(1, _translate("MCMCTreeGUI", "seq like (exact likelihood) SLOW"))
        self.comboBox_3.setItemText(2, _translate("MCMCTreeGUI", "approximate likelihood FAST"))
        self.label_11.setText(_translate("MCMCTreeGUI", "model"))
        self.comboBox_4.setItemText(0, _translate("MCMCTreeGUI", "independent rates"))
        self.comboBox_4.setItemText(1, _translate("MCMCTreeGUI", "global clock"))
        self.comboBox_4.setItemText(2, _translate("MCMCTreeGUI", "correlated rates"))
        self.label_10.setText(_translate("MCMCTreeGUI", "clock"))
        self.doubleSpinBox.setPrefix(_translate("MCMCTreeGUI", "> "))
        self.label_22.setText(_translate("MCMCTreeGUI", "MCMC run"))
        self.doubleSpinBox_19.setPrefix(_translate("MCMCTreeGUI", "< "))
        self.label_20.setText(_translate("MCMCTreeGUI", "rgene_gamma"))
        self.label_19.setText(_translate("MCMCTreeGUI", "alpha_gamma"))
        self.comboBox_8.setToolTip(_translate("MCMCTreeGUI", "Threads for ModelFinder"))
        self.label_7.setText(_translate("MCMCTreeGUI", "print"))
        self.label_17.setText(_translate("MCMCTreeGUI", "BDparas"))
        self.checkBox_11.setText(_translate("MCMCTreeGUI", "Repeat for convergence"))
        self.comboBox_7.setItemText(0, _translate("MCMCTreeGUI", "everything"))
        self.comboBox_7.setItemText(1, _translate("MCMCTreeGUI", "no mcmc sample"))
        self.comboBox_7.setItemText(2, _translate("MCMCTreeGUI", "except branch rates"))
        self.spinBox_20.setPrefix(_translate("MCMCTreeGUI", "nsample: "))
        self.label_15.setText(_translate("MCMCTreeGUI", "alpha"))
        self.label_28.setToolTip(_translate("MCMCTreeGUI", "Threads for ModelFinder"))
        self.label_28.setText(_translate("MCMCTreeGUI", "Threads"))
        self.label_16.setText(_translate("MCMCTreeGUI", "ncatG"))
        self.comboBox_13.setItemText(0, _translate("MCMCTreeGUI", "conditional"))
        self.comboBox_13.setItemText(1, _translate("MCMCTreeGUI", "multiplicative"))
        self.label_21.setText(_translate("MCMCTreeGUI", "sigma2_gamma"))
        self.label_27.setText(_translate("MCMCTreeGUI", "Program for generating Hessian matrix"))
        self.comboBox_14.setItemText(0, _translate("MCMCTreeGUI", "IQ-TREE for all sequences (more models)"))
        self.comboBox_14.setItemText(1, _translate("MCMCTreeGUI", "Baseml for DNA/RNA sequence, Codeml for AA sequence"))
        self.checkBox_12.setText(_translate("MCMCTreeGUI", "Using mixture models"))
        self.pushButton_8.setText(_translate("MCMCTreeGUI", "MCMCTracer"))
        self.pushButton_7.setText(_translate("MCMCTreeGUI", "Preview/Edit configuration"))
        self.pushButton_continue.setText(_translate("MCMCTreeGUI", "Continue Previous Analysis"))
        self.pushButton_9.setText(_translate("MCMCTreeGUI", "Summarize MCMC samples and infer time tree"))
        self.tabWidgetMCMC.setTabText(self.tabWidgetMCMC.indexOf(self.tab), _translate("MCMCTreeGUI", "MCMCTree"))
        self.groupBox_5.setTitle(_translate("MCMCTreeGUI", "r8s parameters setting"))
        self.label_3.setText(_translate("MCMCTreeGUI", "blformat"))
        self.label_6.setText(_translate("MCMCTreeGUI", "Branch lengths"))
        self.comboBox_6.setItemText(0, _translate("MCMCTreeGUI", "persite (numbers of substitutions per site)"))
        self.comboBox_6.setItemText(1, _translate("MCMCTreeGUI", "total (total numbers of substitutions)"))
        self.checkBox.setToolTip(_translate("MCMCTreeGUI", "input trees have ultrametric branch lengths"))
        self.checkBox.setText(_translate("MCMCTreeGUI", "ultrametric"))
        self.checkBox_2.setToolTip(_translate("MCMCTreeGUI", "round estimated branch lengths to nearest integer"))
        self.checkBox_2.setText(_translate("MCMCTreeGUI", "round"))
        self.label_32.setText(_translate("MCMCTreeGUI", "divtime"))
        self.label_33.setText(_translate("MCMCTreeGUI", "method"))
        self.comboBox_9.setItemText(0, _translate("MCMCTreeGUI", "LF (Langley-Fitch)"))
        self.comboBox_9.setItemText(1, _translate("MCMCTreeGUI", "PL (penalized likelihood)"))
        self.label_34.setText(_translate("MCMCTreeGUI", "algorithm"))
        self.label_35.setText(_translate("MCMCTreeGUI", "cvnum"))
        self.checkBox_6.setToolTip(_translate("MCMCTreeGUI", "turn on cross validation"))
        self.checkBox_6.setText(_translate("MCMCTreeGUI", "crossv"))
        self.checkBox_5.setToolTip(_translate("MCMCTreeGUI", "estimate confidence intervals for a node"))
        self.checkBox_5.setText(_translate("MCMCTreeGUI", "confidence"))
        self.checkBox_7.setToolTip(_translate("MCMCTreeGUI", "fossil cross validation removing constrained nodes in turn"))
        self.checkBox_7.setText(_translate("MCMCTreeGUI", "fossilconstrained"))
        self.checkBox_8.setToolTip(_translate("MCMCTreeGUI", "fossil cross validation removing fixed nodes in turn"))
        self.checkBox_8.setText(_translate("MCMCTreeGUI", "fossilfixed"))
        self.label_36.setText(_translate("MCMCTreeGUI", "set"))
        self.label_37.setText(_translate("MCMCTreeGUI", "rates"))
        self.comboBox_12.setItemText(0, _translate("MCMCTreeGUI", "gamma"))
        self.comboBox_12.setItemText(1, _translate("MCMCTreeGUI", "equal"))
        self.label_38.setToolTip(_translate("MCMCTreeGUI", "shape parameter of the gamma distribution"))
        self.label_38.setText(_translate("MCMCTreeGUI", "shape"))
        self.doubleSpinBox_16.setToolTip(_translate("MCMCTreeGUI", "shape parameter of the gamma distribution"))
        self.label_39.setToolTip(_translate("MCMCTreeGUI", "smoothing factor in penalized likelihood"))
        self.label_39.setText(_translate("MCMCTreeGUI", "smoothing"))
        self.doubleSpinBox_17.setToolTip(_translate("MCMCTreeGUI", "smoothing factor in penalized likelihood"))
        self.label_40.setToolTip(_translate("MCMCTreeGUI", "number of initial starts in divtime, using different random combinations of divergence times"))
        self.label_40.setText(_translate("MCMCTreeGUI", "num_time_guesses"))
        self.doubleSpinBox_18.setToolTip(_translate("MCMCTreeGUI", "number of initial starts in divtime, using different random combinations of divergence times"))
        self.label_29.setText(_translate("MCMCTreeGUI", "describe"))
        self.label_30.setText(_translate("MCMCTreeGUI", "plot"))
        self.checkBox_9.setToolTip(_translate("MCMCTreeGUI", "YES: display a table with estimated ages and rates of substitution; NO: only display age information for nodes that have been named using MRCA command"))
        self.checkBox_9.setText(_translate("MCMCTreeGUI", "shownamed"))
        self.checkBox_10.setToolTip(_translate("MCMCTreeGUI", "YES: display a table with estimated ages and rates of substitution; NO: only display age information for nodes that have been named using MRCA command"))
        self.checkBox_10.setText(_translate("MCMCTreeGUI", "Batch process"))
        self.checkBox_3.setText(_translate("MCMCTreeGUI", "removes all trees from memory"))
        self.checkBox_4.setText(_translate("MCMCTreeGUI", "removes all zero branches and converts them to hard polytomies"))
        self.pushButton_12.setText(_translate("MCMCTreeGUI", "Preview configurations"))
        self.pushButton_13.setText(_translate("MCMCTreeGUI", "Generate configuration file and run in Linux system"))
        self.tabWidgetMCMC.setTabText(self.tabWidgetMCMC.indexOf(self.tab_2), _translate("MCMCTreeGUI", "r8s"))
        self.groupBox_3.setTitle(_translate("MCMCTreeGUI", "Run"))
        self.pushButton_2.setText(_translate("MCMCTreeGUI", "Stop"))
        self.pushButton_5.setText(_translate("MCMCTreeGUI", "Start"))
        self.groupBox_4.setTitle(_translate("MCMCTreeGUI", "Progress"))
        self.pushButton_6.setText(_translate("MCMCTreeGUI", "Show log"))

from src.CustomWidget import ArrowPushButton, CheckableComboBox, ClickedLableGif, InputQLineEdit
from uifiles import myRes_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MCMCTreeGUI = QtWidgets.QDialog()
    ui = Ui_MCMCTreeGUI()
    ui.setupUi(MCMCTreeGUI)
    MCMCTreeGUI.show()
    sys.exit(app.exec_())

