# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Work\python\bioinfo_excercise\PhyloSuite\codes\PhyloSuite\uifiles\MACSE.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MACSE(object):
    def setupUi(self, MACSE):
        MACSE.setObjectName("MACSE")
        MACSE.resize(821, 545)
        MACSE.setStyleSheet("")
        MACSE.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(MACSE)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(MACSE)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.comboBox_4 = ListQCombobox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setAcceptDrops(True)
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout.addWidget(self.comboBox_4, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.comboBox_5 = ListQCombobox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_5.sizePolicy().hasHeightForWidth())
        self.comboBox_5.setSizePolicy(sizePolicy)
        self.comboBox_5.setAcceptDrops(True)
        self.comboBox_5.setEditable(True)
        self.comboBox_5.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout.addWidget(self.comboBox_5, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_4.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 2, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.comboBox_7 = ListQCombobox(self.groupBox_4)
        self.comboBox_7.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_7.sizePolicy().hasHeightForWidth())
        self.comboBox_7.setSizePolicy(sizePolicy)
        self.comboBox_7.setAcceptDrops(True)
        self.comboBox_7.setEditable(True)
        self.comboBox_7.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout.addWidget(self.comboBox_7, 2, 1, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_22.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_22.sizePolicy().hasHeightForWidth())
        self.pushButton_22.setSizePolicy(sizePolicy)
        self.pushButton_22.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_22.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_22.setStyleSheet("")
        self.pushButton_22.setText("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout.addWidget(self.pushButton_22, 2, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(63, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_7 = ClickedLableGif(self.groupBox_4)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(MACSE)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(0, 6, 0, 1)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 801, 186))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout.addWidget(self.label_22)
        self.comboBox_9 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_9.sizePolicy().hasHeightForWidth())
        self.comboBox_9.setSizePolicy(sizePolicy)
        self.comboBox_9.setMinimumSize(QtCore.QSize(114, 26))
        self.comboBox_9.setMaximumSize(QtCore.QSize(16777215, 26))
        self.comboBox_9.setStyleSheet("")
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_9)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_2.addWidget(self.label_33)
        self.comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 5, 1, 3)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 1, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox.setPrefix("")
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMaximum(9999.0)
        self.doubleSpinBox.setProperty("value", 30.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_3.addWidget(self.doubleSpinBox, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 1, 2, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_2.setPrefix("")
        self.doubleSpinBox_2.setDecimals(1)
        self.doubleSpinBox_2.setMaximum(9999.0)
        self.doubleSpinBox_2.setProperty("value", 10.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_3.addWidget(self.doubleSpinBox_2, 1, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 1, 4, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_4.setPrefix("")
        self.doubleSpinBox_4.setDecimals(1)
        self.doubleSpinBox_4.setMaximum(9999.0)
        self.doubleSpinBox_4.setProperty("value", 10.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_3.addWidget(self.doubleSpinBox_4, 1, 5, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 1, 6, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_3.setPrefix("")
        self.doubleSpinBox_3.setDecimals(1)
        self.doubleSpinBox_3.setMaximum(9999.0)
        self.doubleSpinBox_3.setProperty("value", 7.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_3.addWidget(self.doubleSpinBox_3, 1, 7, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 2, 0, 1, 1)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_7.setPrefix("")
        self.doubleSpinBox_7.setDecimals(1)
        self.doubleSpinBox_7.setMaximum(9999.0)
        self.doubleSpinBox_7.setSingleStep(0.1)
        self.doubleSpinBox_7.setProperty("value", 1.0)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.gridLayout_3.addWidget(self.doubleSpinBox_7, 2, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 2, 2, 1, 1)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_8.setPrefix("")
        self.doubleSpinBox_8.setDecimals(1)
        self.doubleSpinBox_8.setMaximum(9999.0)
        self.doubleSpinBox_8.setSingleStep(0.1)
        self.doubleSpinBox_8.setProperty("value", 7.0)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.gridLayout_3.addWidget(self.doubleSpinBox_8, 2, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 2, 4, 1, 1)
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_9.setPrefix("")
        self.doubleSpinBox_9.setDecimals(1)
        self.doubleSpinBox_9.setMaximum(9999.0)
        self.doubleSpinBox_9.setSingleStep(0.1)
        self.doubleSpinBox_9.setProperty("value", 0.9)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.gridLayout_3.addWidget(self.doubleSpinBox_9, 2, 5, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 2, 6, 1, 1)
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_10.setPrefix("")
        self.doubleSpinBox_10.setDecimals(1)
        self.doubleSpinBox_10.setMaximum(9999.0)
        self.doubleSpinBox_10.setSingleStep(0.1)
        self.doubleSpinBox_10.setProperty("value", 6.3)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.gridLayout_3.addWidget(self.doubleSpinBox_10, 2, 7, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 3, 0, 1, 1)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_5.setPrefix("")
        self.doubleSpinBox_5.setDecimals(1)
        self.doubleSpinBox_5.setMaximum(9999.0)
        self.doubleSpinBox_5.setProperty("value", 50.0)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout_3.addWidget(self.doubleSpinBox_5, 3, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 3, 2, 1, 1)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_6.setPrefix("")
        self.doubleSpinBox_6.setDecimals(1)
        self.doubleSpinBox_6.setMaximum(9999.0)
        self.doubleSpinBox_6.setProperty("value", 17.0)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout_3.addWidget(self.doubleSpinBox_6, 3, 3, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_34 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_7.addWidget(self.label_34)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_7.addWidget(self.lineEdit)
        self.checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_7.addWidget(self.checkBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 3, 4, 1, 4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_35 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_6.addWidget(self.label_35)
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_11.setPrefix("")
        self.doubleSpinBox_11.setDecimals(1)
        self.doubleSpinBox_11.setMaximum(1.0)
        self.doubleSpinBox_11.setSingleStep(0.1)
        self.doubleSpinBox_11.setProperty("value", 0.5)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_11)
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_6.addWidget(self.label_36)
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_12.setPrefix("")
        self.doubleSpinBox_12.setDecimals(1)
        self.doubleSpinBox_12.setMaximum(1.0)
        self.doubleSpinBox_12.setSingleStep(0.1)
        self.doubleSpinBox_12.setProperty("value", 0.5)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_12)
        self.label_37 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_6.addWidget(self.label_37)
        self.spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox.setMinimum(-99999)
        self.spinBox.setMaximum(99999)
        self.spinBox.setProperty("value", -1)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_6.addWidget(self.spinBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 4, 0, 1, 8)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_38 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_8.addWidget(self.label_38)
        self.comboBox_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_2)
        self.label_39 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_8.addWidget(self.label_39)
        self.comboBox_3 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_3)
        self.label_40 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_8.addWidget(self.label_40)
        self.comboBox_6 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        self.comboBox_6.setObjectName("comboBox_6")
        self.horizontalLayout_8.addWidget(self.comboBox_6)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 5, 0, 1, 8)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(MACSE)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = ArrowPushButton(self.groupBox_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/resourses/if_start_60207.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/picture/resourses/if_Delete_1493279.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(MACSE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/picture/resourses/Eye_Care_Services-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_2.addWidget(self.pushButton_9)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(MACSE)
        self.comboBox.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(0)
        self.comboBox_3.setCurrentIndex(0)
        self.comboBox_6.setCurrentIndex(-1)
        self.checkBox_2.toggled['bool'].connect(self.comboBox_7.setEnabled)
        self.checkBox_2.toggled['bool'].connect(self.pushButton_22.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MACSE)
        MACSE.setTabOrder(self.pushButton_3, self.comboBox_4)
        MACSE.setTabOrder(self.comboBox_4, self.comboBox_9)
        MACSE.setTabOrder(self.comboBox_9, self.pushButton_9)

    def retranslateUi(self, MACSE):
        _translate = QtCore.QCoreApplication.translate
        MACSE.setWindowTitle(_translate("MACSE", "MACSE"))
        self.groupBox_4.setTitle(_translate("MACSE", "Input"))
        self.label_4.setToolTip(_translate("MACSE", "Sequence file (fasta) containing reliable nucleotide sequences"))
        self.label_4.setText(_translate("MACSE", "Seq.:"))
        self.comboBox_4.setToolTip(_translate("MACSE", "Sequence file (fasta) containing reliable nucleotide sequences"))
        self.label_8.setToolTip(_translate("MACSE", "Sequence file (fasta) containing less reliable nucleotide sequences (e.g. pseudogenes). OPTIONAL!"))
        self.label_8.setText(_translate("MACSE", "Seq_lr.:"))
        self.comboBox_5.setToolTip(_translate("MACSE", "Sequence file (fasta) containing less reliable nucleotide sequences (e.g. pseudogenes)"))
        self.checkBox_2.setToolTip(_translate("MACSE", "Improves previously computed alignments via “refineAlignment” subprogram."))
        self.checkBox_2.setText(_translate("MACSE", "Refine:"))
        self.comboBox_7.setToolTip(_translate("MACSE", "Improves previously computed alignments via “refineAlignment” subprogram."))
        self.label_5.setText(_translate("MACSE", "<html><head/><body><p>If you choose &quot;<span style=\" color:#ff0000;\">Refine</span>&quot; (refineAlignment), &quot;<span style=\" color:#ff0000;\">Seq.</span>&quot; is optional. Click <a href=\"https://bioweb.supagro.inra.fr/macse/index.php?menu=intro\"><span style=\" text-decoration: underline; color:#0000ff;\">here</span></a> to learn more about MACSE.</p></body></html>"))
        self.label_3.setText(_translate("MACSE", "Demo:"))
        self.label_7.setToolTip(_translate("MACSE", "Brief example"))
        self.groupBox_2.setTitle(_translate("MACSE", "Parameter"))
        self.label_22.setText(_translate("MACSE", "Code Table:"))
        self.comboBox_9.setItemText(0, _translate("MACSE", "1 The standard code"))
        self.comboBox_9.setItemText(1, _translate("MACSE", "2 Vertebrate mitochondrial code"))
        self.comboBox_9.setItemText(2, _translate("MACSE", "3 The Yeast Mitochondrial Code"))
        self.comboBox_9.setItemText(3, _translate("MACSE", "4 Mold, Protozoan, and Coelenterate Mitochondrial code and Mycoplasma/Spiroplasma code"))
        self.comboBox_9.setItemText(4, _translate("MACSE", "5 Invertebrate mitochondrial"))
        self.comboBox_9.setItemText(5, _translate("MACSE", "6 The Ciliate, Dasycladacean and Hexamita Nuclear Code"))
        self.comboBox_9.setItemText(6, _translate("MACSE", "9 Echinoderm and Flatworm mitochondrial code"))
        self.comboBox_9.setItemText(7, _translate("MACSE", "10 The Euplotid Nuclear Code"))
        self.comboBox_9.setItemText(8, _translate("MACSE", "11 The Bacterial, Archaeal and Plant Plastid Code"))
        self.comboBox_9.setItemText(9, _translate("MACSE", "12 The Alternative Yeast Nuclear Code"))
        self.comboBox_9.setItemText(10, _translate("MACSE", "13 Ascidian mitochondrial code"))
        self.comboBox_9.setItemText(11, _translate("MACSE", "14 Alternative flatworm mitochondrial code"))
        self.comboBox_9.setItemText(12, _translate("MACSE", "16 Chlorophycean Mitochondrial Code"))
        self.comboBox_9.setItemText(13, _translate("MACSE", "21 Trematode Mitochondrial Code"))
        self.comboBox_9.setItemText(14, _translate("MACSE", "22 Scenedesmus obliquus Mitochondrial Code"))
        self.comboBox_9.setItemText(15, _translate("MACSE", "23 Thraustochytrium Mitochondrial Code"))
        self.comboBox_9.setItemText(16, _translate("MACSE", "24 Pterobranchia Mitochondrial Code"))
        self.comboBox_9.setItemText(17, _translate("MACSE", "25 Candidate Division SR1 and Gracilibacteria Code"))
        self.comboBox_9.setItemText(18, _translate("MACSE", "26 Pachysolen tannophilus Nuclear Code"))
        self.comboBox_9.setItemText(19, _translate("MACSE", "27 Karyorelict Nuclear"))
        self.comboBox_9.setItemText(20, _translate("MACSE", "28 Condylostoma Nuclear"))
        self.comboBox_9.setItemText(21, _translate("MACSE", "29 Mesodinium Nuclear"))
        self.comboBox_9.setItemText(22, _translate("MACSE", "30 Peritrich Nuclear"))
        self.comboBox_9.setItemText(23, _translate("MACSE", "31 Blastocrithidia Nuclear"))
        self.label_33.setToolTip(_translate("MACSE", "Compressed amino acid alphabet used to compute initial pairwise distances or to identify homologous fragments."))
        self.label_33.setText(_translate("MACSE", "Alphabet_AA:"))
        self.comboBox.setToolTip(_translate("MACSE", "Compressed amino acid alphabet used to compute initial pairwise distances or to identify homologous fragments."))
        self.comboBox.setItemText(0, _translate("MACSE", "SE_B_8"))
        self.comboBox.setItemText(1, _translate("MACSE", "Dayhoff_6"))
        self.comboBox.setItemText(2, _translate("MACSE", "Li_A_10"))
        self.comboBox.setItemText(3, _translate("MACSE", "Li_B_10"))
        self.comboBox.setItemText(4, _translate("MACSE", "Murphy_10"))
        self.comboBox.setItemText(5, _translate("MACSE", "SE_B_10"))
        self.comboBox.setItemText(6, _translate("MACSE", "SE_B_14"))
        self.comboBox.setItemText(7, _translate("MACSE", "SE_B_6"))
        self.comboBox.setItemText(8, _translate("MACSE", "SE_V_10"))
        self.comboBox.setItemText(9, _translate("MACSE", "Solis_D_10"))
        self.comboBox.setItemText(10, _translate("MACSE", "Solis_G_10"))
        self.label_23.setToolTip(_translate("MACSE", "Cost of a frameshift in reliable sequences (those of \"seq.\" file)"))
        self.label_23.setText(_translate("MACSE", "fs: "))
        self.doubleSpinBox.setToolTip(_translate("MACSE", "Cost of a frameshift in reliable sequences (those of \"seq.\" file)"))
        self.label_24.setToolTip(_translate("MACSE", "Cost of a frameshift in less reliable sequences (those of \"seq_lr\" file)"))
        self.label_24.setText(_translate("MACSE", "fs_lr: "))
        self.doubleSpinBox_2.setToolTip(_translate("MACSE", "Cost of a frameshift in less reliable sequences (those of \"seq_lr\" file)"))
        self.label_26.setToolTip(_translate("MACSE", "Cost of a terminal frameshift (those in the first and last codon) in a reliable sequences (those of \"seq.\" file)"))
        self.label_26.setText(_translate("MACSE", "fs_term: "))
        self.doubleSpinBox_4.setToolTip(_translate("MACSE", "Cost of a terminal frameshift (those in the first and last codon) in a reliable sequences (those of \"seq.\" file)"))
        self.label_25.setToolTip(_translate("MACSE", "Cost of a terminal frameshift (those in the first and last codon) in a less reliable sequences (those of \"seq_lr\" file)"))
        self.label_25.setText(_translate("MACSE", "fs_lr_term: "))
        self.doubleSpinBox_3.setToolTip(_translate("MACSE", "Cost of a terminal frameshift (those in the first and last codon) in a less reliable sequences (those of \"seq_lr\" file)"))
        self.label_29.setToolTip(_translate("MACSE", "Cost of internal gap extension"))
        self.label_29.setText(_translate("MACSE", "gap_ext:"))
        self.doubleSpinBox_7.setToolTip(_translate("MACSE", "Cost of internal gap extension"))
        self.label_31.setToolTip(_translate("MACSE", "Cost of internal gap opening"))
        self.label_31.setText(_translate("MACSE", "gap_op:"))
        self.doubleSpinBox_8.setToolTip(_translate("MACSE", "Cost of internal gap opening"))
        self.label_30.setToolTip(_translate("MACSE", "Cost of terminal gap extension (e.g. those before the first nucleotide and after the last one)"))
        self.label_30.setText(_translate("MACSE", "gap_ext_term:"))
        self.doubleSpinBox_9.setToolTip(_translate("MACSE", "Cost of terminal gap extension (e.g. those before the first nucleotide and after the last one)"))
        self.label_32.setToolTip(_translate("MACSE", "Cost of terminal gap opening (e.g. those before the first nucleotide and after the last one)"))
        self.label_32.setText(_translate("MACSE", "gap_op_term:"))
        self.doubleSpinBox_10.setToolTip(_translate("MACSE", "Cost of terminal gap opening (e.g. those before the first nucleotide and after the last one)"))
        self.label_27.setToolTip(_translate("MACSE", "Cost of a stop codon in reliable sequences, it should be less than twice the cost of a frameshift in those sequences"))
        self.label_27.setText(_translate("MACSE", "stop:"))
        self.doubleSpinBox_5.setToolTip(_translate("MACSE", "Cost of a stop codon in reliable sequences, it should be less than twice the cost of a frameshift in those sequences"))
        self.label_28.setToolTip(_translate("MACSE", "Cost of a stop codon in less reliable sequences, it should be less than twice the cost of a frameshift in those sequences"))
        self.label_28.setText(_translate("MACSE", "stop_lr:"))
        self.doubleSpinBox_6.setToolTip(_translate("MACSE", "Cost of a stop codon in less reliable sequences, it should be less than twice the cost of a frameshift in those sequences"))
        self.label_34.setToolTip(_translate("MACSE", "Extra nucleotide characters to consider as N"))
        self.label_34.setText(_translate("MACSE", "allow_NT:"))
        self.lineEdit.setToolTip(_translate("MACSE", "Extra nucleotide characters to consider as N"))
        self.lineEdit.setPlaceholderText(_translate("MACSE", "#?"))
        self.checkBox.setToolTip(_translate("MACSE", "Disables ambiguities management (e.g. a \'TCN\' codon will be translated into an unknown amono acid instead of a serine (S))"))
        self.checkBox.setText(_translate("MACSE", "ambi_OFF"))
        self.label_35.setToolTip(_translate("MACSE", "If smaller than 1 each refinement loop will be faster than the previous one by focusing on a smaller interval alignment improvement steps (the lower this value the faster the refinements, possitive values [0-1])"))
        self.label_35.setText(_translate("MACSE", "local_realign_dec:"))
        self.doubleSpinBox_11.setToolTip(_translate("MACSE", "If smaller than 1 each refinement loop will be faster than the previous one by focusing on a smaller interval alignment improvement steps (the lower this value the faster the refinements, possitive values [0-1])"))
        self.label_36.setToolTip(_translate("MACSE", "If smaller than 1 the first refinement loop will consider only local improvement (the lower this value the faster the initial refinement, possible values [0-1])"))
        self.label_36.setText(_translate("MACSE", "local_realign_init:"))
        self.doubleSpinBox_12.setToolTip(_translate("MACSE", "If smaller than 1 the first refinement loop will consider only local improvement (the lower this value the faster the initial refinement, possible values [0-1])"))
        self.label_37.setToolTip(_translate("MACSE", "The max number of refinement iterations when optimizing alignment (-1 = no iteration limit)"))
        self.label_37.setText(_translate("MACSE", "max_refine_iter:"))
        self.spinBox.setToolTip(_translate("MACSE", "The max number of refinement iterations when optimizing alignment (-1 = no iteration limit)"))
        self.label_38.setToolTip(_translate("MACSE", "Optimization parameter (0=none, 1=basic leaf cut, 2=standard branch cut)"))
        self.label_38.setText(_translate("MACSE", "optimization:"))
        self.comboBox_2.setToolTip(_translate("MACSE", "Optimization parameter (0=none, 1=basic leaf cut, 2=standard branch cut)"))
        self.comboBox_2.setItemText(0, _translate("MACSE", "STANDARD"))
        self.comboBox_2.setItemText(1, _translate("MACSE", "NONE"))
        self.comboBox_2.setItemText(2, _translate("MACSE", "BASIC"))
        self.label_39.setToolTip(_translate("MACSE", "Amino acid score matrix to use"))
        self.label_39.setText(_translate("MACSE", "score matrix:"))
        self.comboBox_3.setToolTip(_translate("MACSE", "Amino acid score matrix to use"))
        self.comboBox_3.setItemText(0, _translate("MACSE", "BLOSUM62"))
        self.comboBox_3.setItemText(1, _translate("MACSE", "VTML200_BIS"))
        self.comboBox_3.setItemText(2, _translate("MACSE", "VTML240"))
        self.label_40.setToolTip(_translate("MACSE", "Amino acid score matrix to use"))
        self.label_40.setText(_translate("MACSE", "thread:"))
        self.comboBox_6.setToolTip(_translate("MACSE", "Amino acid score matrix to use"))
        self.groupBox_3.setTitle(_translate("MACSE", "Run"))
        self.pushButton.setText(_translate("MACSE", "Start"))
        self.pushButton_2.setText(_translate("MACSE", "Stop"))
        self.groupBox.setTitle(_translate("MACSE", "Progress"))
        self.pushButton_9.setText(_translate("MACSE", "Show log"))

from src.CustomWidget import ArrowPushButton, ClickedLableGif, ListQCombobox
from uifiles import myRes_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MACSE = QtWidgets.QDialog()
    ui = Ui_MACSE()
    ui.setupUi(MACSE)
    MACSE.show()
    sys.exit(app.exec_())

