# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\F\Work\python\bioinfo_excercise\PhyloSuite\codes\PhyloSuite_gitee\PhyloSuite\uifiles\MCMCTracer.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MCMCTracer(object):
    def setupUi(self, MCMCTracer):
        MCMCTracer.setObjectName("MCMCTracer")
        MCMCTracer.resize(1191, 779)
        MCMCTracer.setMinimumSize(QtCore.QSize(1187, 762))
        self.centralwidget = QtWidgets.QWidget(MCMCTracer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget1 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget1.setObjectName("tabWidget1")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget1 = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget1.setAcceptDrops(True)
        self.tableWidget1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget1.setDragEnabled(True)
        self.tableWidget1.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableWidget1.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tableWidget1.setAlternatingRowColors(True)
        self.tableWidget1.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget1.setObjectName("tableWidget1")
        self.tableWidget1.setColumnCount(3)
        self.tableWidget1.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(2, item)
        self.tableWidget1.horizontalHeader().setDefaultSectionSize(75)
        self.tableWidget1.horizontalHeader().setMinimumSectionSize(15)
        self.tableWidget1.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget1.horizontalHeader().setStretchLastSection(True)
        self.tableWidget1.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget1.verticalHeader().setMinimumSectionSize(15)
        self.tableWidget1.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tableWidget1, 2, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/resourses/Open_folder_add_512px_1186192_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 0, 1, 2)
        self.verticalLayout_15.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget2 = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget2.setAcceptDrops(True)
        self.tableWidget2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget2.setDragEnabled(True)
        self.tableWidget2.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableWidget2.setAlternatingRowColors(True)
        self.tableWidget2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget2.setObjectName("tableWidget2")
        self.tableWidget2.setColumnCount(3)
        self.tableWidget2.setRowCount(20)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(2, item)
        self.tableWidget2.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget2.horizontalHeader().setMinimumSectionSize(15)
        self.tableWidget2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget2.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget2.verticalHeader().setMinimumSectionSize(15)
        self.horizontalLayout.addWidget(self.tableWidget2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(1, 12)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget3 = QtWidgets.QTableWidget(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget3.setFont(font)
        self.tableWidget3.setAcceptDrops(True)
        self.tableWidget3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget3.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableWidget3.setAlternatingRowColors(True)
        self.tableWidget3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget3.setRowCount(6)
        self.tableWidget3.setObjectName("tableWidget3")
        self.tableWidget3.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableWidget3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget3.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        brush = QtGui.QBrush(QtGui.QColor(202, 202, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget3.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(202, 202, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget3.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableWidget3.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget3.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        brush = QtGui.QBrush(QtGui.QColor(202, 202, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget3.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(202, 202, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget3.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableWidget3.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget3.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        brush = QtGui.QBrush(QtGui.QColor(202, 202, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget3.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(202, 202, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.tableWidget3.setItem(5, 1, item)
        self.tableWidget3.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget3.horizontalHeader().setDefaultSectionSize(410)
        self.tableWidget3.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget3.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget3.horizontalHeader().setStretchLastSection(True)
        self.tableWidget3.verticalHeader().setVisible(False)
        self.tableWidget3.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget3.verticalHeader().setMinimumSectionSize(20)
        self.horizontalLayout_2.addWidget(self.tableWidget3)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.widget5 = QtWidgets.QTabWidget(self.tab)
        self.widget5.setObjectName("widget5")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget1 = QtWidgets.QWidget(self.tab_3)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3.addWidget(self.widget1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_color_1 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_color_1.setObjectName("pushButton_color_1")
        self.horizontalLayout_5.addWidget(self.pushButton_color_1)
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.comboBox_bin = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_bin.setObjectName("comboBox_bin")
        self.comboBox_bin.addItem("")
        self.comboBox_bin.addItem("")
        self.comboBox_bin.addItem("")
        self.comboBox_bin.addItem("")
        self.comboBox_bin.addItem("")
        self.comboBox_bin.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_bin)
        self.radioButton = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_5.addWidget(self.radioButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.setStretch(0, 20)
        self.verticalLayout_3.setStretch(1, 1)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.widget5.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget4 = QtWidgets.QWidget(self.tab_6)
        self.widget4.setObjectName("widget4")
        self.verticalLayout_11.addWidget(self.widget4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_color_3 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_color_3.setObjectName("pushButton_color_3")
        self.horizontalLayout_8.addWidget(self.pushButton_color_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.verticalLayout_11.setStretch(0, 20)
        self.verticalLayout_11.setStretch(1, 1)
        self.verticalLayout_13.addLayout(self.verticalLayout_11)
        self.widget5.addTab(self.tab_6, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget2 = QtWidgets.QWidget(self.tab_4)
        self.widget2.setObjectName("widget2")
        self.verticalLayout_5.addWidget(self.widget2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.pushButton_color_2 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_color_2.setObjectName("pushButton_color_2")
        self.horizontalLayout_3.addWidget(self.pushButton_color_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.setStretch(0, 20)
        self.verticalLayout_5.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.widget5.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget6 = QtWidgets.QWidget(self.tab_5)
        self.widget6.setObjectName("widget6")
        self.verticalLayout_12.addWidget(self.widget6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.verticalLayout_12.setStretch(0, 20)
        self.verticalLayout_12.setStretch(1, 1)
        self.verticalLayout_14.addLayout(self.verticalLayout_12)
        self.widget5.addTab(self.tab_5, "")
        self.verticalLayout_7.addWidget(self.widget5)
        self.verticalLayout_7.setStretch(0, 10)
        self.verticalLayout_7.setStretch(1, 23)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.tabWidget1.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.splitter_2 = QtWidgets.QSplitter(self.tab_2)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton.setText("")
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(35, 35))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 1, 1, 1)
        self.tableWidget4 = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableWidget4.setAcceptDrops(True)
        self.tableWidget4.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget4.setAlternatingRowColors(True)
        self.tableWidget4.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget4.setObjectName("tableWidget4")
        self.tableWidget4.setColumnCount(3)
        self.tableWidget4.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4.setHorizontalHeaderItem(2, item)
        self.tableWidget4.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget4.horizontalHeader().setMinimumSectionSize(150)
        self.tableWidget4.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget4.horizontalHeader().setStretchLastSection(True)
        self.tableWidget4.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget4.verticalHeader().setMinimumSectionSize(15)
        self.tableWidget4.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tableWidget4, 0, 0, 2, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_2)
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setOpenExternalLinks(True)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_8.addWidget(self.label_23)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox_6 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_6)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(16)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.groupBox_5 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget3 = QtWidgets.QWidget(self.groupBox_5)
        self.widget3.setObjectName("widget3")
        self.gridLayout_5.addWidget(self.widget3, 0, 2, 1, 1)
        self.verticalLayout_9.addWidget(self.splitter_2)
        self.tabWidget1.addTab(self.tab_2, "")
        self.verticalLayout_4.addWidget(self.tabWidget1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/picture/resourses/Save-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        MCMCTracer.setCentralWidget(self.centralwidget)

        self.retranslateUi(MCMCTracer)
        self.tabWidget1.setCurrentIndex(0)
        self.widget5.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MCMCTracer)

    def retranslateUi(self, MCMCTracer):
        _translate = QtCore.QCoreApplication.translate
        MCMCTracer.setWindowTitle(_translate("MCMCTracer", "MCMCTracer"))
        self.groupBox.setTitle(_translate("MCMCTracer", "Files"))
        item = self.tableWidget1.verticalHeaderItem(0)
        item.setText(_translate("MCMCTracer", "1"))
        item = self.tableWidget1.verticalHeaderItem(1)
        item.setText(_translate("MCMCTracer", "2"))
        item = self.tableWidget1.horizontalHeaderItem(0)
        item.setText(_translate("MCMCTracer", "TraceFile"))
        item = self.tableWidget1.horizontalHeaderItem(1)
        item.setText(_translate("MCMCTracer", "States"))
        item = self.tableWidget1.horizontalHeaderItem(2)
        item.setText(_translate("MCMCTracer", "Sampfreq"))
        self.pushButton_2.setText(_translate("MCMCTracer", "Open"))
        self.groupBox_2.setTitle(_translate("MCMCTracer", "Traces"))
        item = self.tableWidget2.verticalHeaderItem(0)
        item.setText(_translate("MCMCTracer", "1"))
        item = self.tableWidget2.verticalHeaderItem(1)
        item.setText(_translate("MCMCTracer", "2"))
        item = self.tableWidget2.verticalHeaderItem(2)
        item.setText(_translate("MCMCTracer", "3"))
        item = self.tableWidget2.verticalHeaderItem(3)
        item.setText(_translate("MCMCTracer", "4"))
        item = self.tableWidget2.verticalHeaderItem(4)
        item.setText(_translate("MCMCTracer", "5"))
        item = self.tableWidget2.verticalHeaderItem(5)
        item.setText(_translate("MCMCTracer", "6"))
        item = self.tableWidget2.verticalHeaderItem(6)
        item.setText(_translate("MCMCTracer", "7"))
        item = self.tableWidget2.verticalHeaderItem(7)
        item.setText(_translate("MCMCTracer", "8"))
        item = self.tableWidget2.verticalHeaderItem(8)
        item.setText(_translate("MCMCTracer", "9"))
        item = self.tableWidget2.verticalHeaderItem(9)
        item.setText(_translate("MCMCTracer", "10"))
        item = self.tableWidget2.verticalHeaderItem(10)
        item.setText(_translate("MCMCTracer", "11"))
        item = self.tableWidget2.verticalHeaderItem(11)
        item.setText(_translate("MCMCTracer", "12"))
        item = self.tableWidget2.verticalHeaderItem(12)
        item.setText(_translate("MCMCTracer", "13"))
        item = self.tableWidget2.verticalHeaderItem(13)
        item.setText(_translate("MCMCTracer", "14"))
        item = self.tableWidget2.verticalHeaderItem(14)
        item.setText(_translate("MCMCTracer", "15"))
        item = self.tableWidget2.verticalHeaderItem(15)
        item.setText(_translate("MCMCTracer", "16"))
        item = self.tableWidget2.verticalHeaderItem(16)
        item.setText(_translate("MCMCTracer", "17"))
        item = self.tableWidget2.verticalHeaderItem(17)
        item.setText(_translate("MCMCTracer", "18"))
        item = self.tableWidget2.verticalHeaderItem(18)
        item.setText(_translate("MCMCTracer", "19"))
        item = self.tableWidget2.verticalHeaderItem(19)
        item.setText(_translate("MCMCTracer", "20"))
        item = self.tableWidget2.horizontalHeaderItem(0)
        item.setText(_translate("MCMCTracer", "Statistic"))
        item = self.tableWidget2.horizontalHeaderItem(1)
        item.setText(_translate("MCMCTracer", "Mean"))
        item = self.tableWidget2.horizontalHeaderItem(2)
        item.setText(_translate("MCMCTracer", "ESS"))
        self.groupBox_3.setTitle(_translate("MCMCTracer", "Summary statictic"))
        item = self.tableWidget3.horizontalHeaderItem(0)
        item.setText(_translate("MCMCTracer", "PARAMETER"))
        item = self.tableWidget3.horizontalHeaderItem(1)
        item.setText(_translate("MCMCTracer", "VALUE"))
        __sortingEnabled = self.tableWidget3.isSortingEnabled()
        self.tableWidget3.setSortingEnabled(False)
        item = self.tableWidget3.item(0, 0)
        item.setText(_translate("MCMCTracer", "mean"))
        item = self.tableWidget3.item(1, 0)
        item.setText(_translate("MCMCTracer", "median"))
        item = self.tableWidget3.item(2, 0)
        item.setText(_translate("MCMCTracer", "value range"))
        item = self.tableWidget3.item(3, 0)
        item.setText(_translate("MCMCTracer", "95% HPD interval"))
        item = self.tableWidget3.item(4, 0)
        item.setText(_translate("MCMCTracer", "ESS-bulk"))
        item = self.tableWidget3.item(5, 0)
        item.setText(_translate("MCMCTracer", "ESS-tail"))
        self.tableWidget3.setSortingEnabled(__sortingEnabled)
        self.pushButton_color_1.setText(_translate("MCMCTracer", "Color"))
        self.label.setText(_translate("MCMCTracer", "Bins:"))
        self.comboBox_bin.setCurrentText(_translate("MCMCTracer", "50"))
        self.comboBox_bin.setItemText(0, _translate("MCMCTracer", "50"))
        self.comboBox_bin.setItemText(1, _translate("MCMCTracer", "10"))
        self.comboBox_bin.setItemText(2, _translate("MCMCTracer", "20"))
        self.comboBox_bin.setItemText(3, _translate("MCMCTracer", "100"))
        self.comboBox_bin.setItemText(4, _translate("MCMCTracer", "200"))
        self.comboBox_bin.setItemText(5, _translate("MCMCTracer", "1000"))
        self.radioButton.setText(_translate("MCMCTracer", "95% HDI"))
        self.widget5.setTabText(self.widget5.indexOf(self.tab_3), _translate("MCMCTracer", "Estimates"))
        self.pushButton_color_3.setText(_translate("MCMCTracer", "Color"))
        self.widget5.setTabText(self.widget5.indexOf(self.tab_6), _translate("MCMCTracer", "Esti-dist"))
        self.checkBox.setText(_translate("MCMCTracer", "Line Plot"))
        self.pushButton_color_2.setText(_translate("MCMCTracer", "Color"))
        self.widget5.setTabText(self.widget5.indexOf(self.tab_4), _translate("MCMCTracer", "Trace"))
        self.widget5.setTabText(self.widget5.indexOf(self.tab_5), _translate("MCMCTracer", "ESS Trace"))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.tab), _translate("MCMCTracer", "Trace"))
        self.groupBox_4.setTitle(_translate("MCMCTracer", "Files"))
        item = self.tableWidget4.verticalHeaderItem(0)
        item.setText(_translate("MCMCTracer", "1"))
        item = self.tableWidget4.verticalHeaderItem(1)
        item.setText(_translate("MCMCTracer", "2"))
        item = self.tableWidget4.horizontalHeaderItem(0)
        item.setText(_translate("MCMCTracer", "Files"))
        item = self.tableWidget4.horizontalHeaderItem(1)
        item.setText(_translate("MCMCTracer", "Seed"))
        item = self.tableWidget4.horizontalHeaderItem(2)
        item.setText(_translate("MCMCTracer", "Posterior mean times"))
        self.label_23.setText(_translate("MCMCTracer", "<html><head/><body><p>Compare the output of the two analyses. They should be similar <span style=\" font-weight:600; color:#ff0000;\">(but not identical)</span>.</p></body></html>"))
        self.groupBox_6.setTitle(_translate("MCMCTracer", "Select Combination"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MCMCTracer", "run* & run*"))
        self.groupBox_5.setTitle(_translate("MCMCTracer", "Convergence Check"))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.tab_2), _translate("MCMCTracer", "Convergence"))
        self.pushButton_5.setToolTip(_translate("MCMCTracer", "<html><head/><body><p><span style=\" font-weight:600;\">Save the figure</span></p></body></html>"))
        self.pushButton_5.setText(_translate("MCMCTracer", "Save current figure"))

from uifiles import myRes_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MCMCTracer = QtWidgets.QMainWindow()
    ui = Ui_MCMCTracer()
    ui.setupUi(MCMCTracer)
    MCMCTracer.show()
    sys.exit(app.exec_())

