# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\works\phylosuite\PhyloSuite_gitee\PhyloSuite\uifiles\muscle.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MUSCLE(object):
    def setupUi(self, MUSCLE):
        MUSCLE.setObjectName("MUSCLE")
        MUSCLE.resize(941, 662)
        MUSCLE.setStyleSheet("")
        MUSCLE.setSizeGripEnabled(True)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(MUSCLE)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(MUSCLE)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.comboBox_4 = ListQCombobox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setAcceptDrops(True)
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_4.setObjectName("comboBox_4")
        self.horizontalLayout_6.addWidget(self.comboBox_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.AA_radioButton_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.AA_radioButton_2.setChecked(False)
        self.AA_radioButton_2.setObjectName("AA_radioButton_2")
        self.horizontalLayout_4.addWidget(self.AA_radioButton_2)
        self.PCG_radioButton_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.PCG_radioButton_2.setEnabled(True)
        self.PCG_radioButton_2.setChecked(True)
        self.PCG_radioButton_2.setObjectName("PCG_radioButton_2")
        self.horizontalLayout_4.addWidget(self.PCG_radioButton_2)
        self.RNAs_radioButton_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.RNAs_radioButton_2.setObjectName("RNAs_radioButton_2")
        self.horizontalLayout_4.addWidget(self.RNAs_radioButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.label_7 = ClickedLableGif(self.groupBox_4)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(MUSCLE)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setMinimumSize(QtCore.QSize(13, 26))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_3, 0, 1, 1, 3)
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 1, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_2.addWidget(self.checkBox_3, 3, 0, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_9.sizePolicy().hasHeightForWidth())
        self.comboBox_9.setSizePolicy(sizePolicy)
        self.comboBox_9.setMinimumSize(QtCore.QSize(114, 26))
        self.comboBox_9.setMaximumSize(QtCore.QSize(16777215, 26))
        self.comboBox_9.setStyleSheet("")
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_9, 1, 1, 1, 3)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox.setEnabled(False)
        self.spinBox.setMaximum(999999999)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 2, 1, 1, 3)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_2.addWidget(self.checkBox_6, 2, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_2.setEnabled(False)
        self.spinBox_2.setMaximum(999999999)
        self.spinBox_2.setProperty("value", 4)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_2.addWidget(self.spinBox_2, 3, 1, 1, 3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_2.addWidget(self.checkBox_4, 4, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_2.addWidget(self.checkBox_5, 5, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_3.setEnabled(False)
        self.spinBox_3.setMaximum(999999999)
        self.spinBox_3.setProperty("value", 2)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_2.addWidget(self.spinBox_3, 4, 1, 1, 3)
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_4.setEnabled(False)
        self.spinBox_4.setMaximum(999999999)
        self.spinBox_4.setProperty("value", 100)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_2.addWidget(self.spinBox_4, 5, 1, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_26 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_2.addWidget(self.label_26)
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        self.comboBox_6.setMinimumSize(QtCore.QSize(13, 26))
        self.comboBox_6.setObjectName("comboBox_6")
        self.horizontalLayout_2.addWidget(self.comboBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_2.addWidget(self.checkBox_7)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMinimumSize(QtCore.QSize(13, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout.addWidget(self.label_25)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_5.sizePolicy().hasHeightForWidth())
        self.comboBox_5.setSizePolicy(sizePolicy)
        self.comboBox_5.setMinimumSize(QtCore.QSize(13, 26))
        self.comboBox_5.setObjectName("comboBox_5")
        self.horizontalLayout.addWidget(self.comboBox_5)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(MUSCLE)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton = ArrowPushButton(self.groupBox_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/resourses/if_start_60207.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/picture/resourses/if_Delete_1493279.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(MUSCLE)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout.addWidget(self.progressBar_2, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/picture/resourses/Eye_Care_Services-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.label_26.setBuddy(self.comboBox_2)
        self.label_25.setBuddy(self.comboBox_2)

        self.retranslateUi(MUSCLE)
        self.checkBox_6.toggled['bool'].connect(self.spinBox.setEnabled)
        self.checkBox_3.toggled['bool'].connect(self.spinBox_2.setEnabled)
        self.checkBox_4.toggled['bool'].connect(self.spinBox_3.setEnabled)
        self.checkBox_5.toggled['bool'].connect(self.spinBox_4.setEnabled)
        self.checkBox_7.toggled['bool'].connect(self.comboBox_2.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MUSCLE)
        MUSCLE.setTabOrder(self.pushButton_3, self.comboBox_3)
        MUSCLE.setTabOrder(self.comboBox_3, self.comboBox_4)
        MUSCLE.setTabOrder(self.comboBox_4, self.comboBox_2)
        MUSCLE.setTabOrder(self.comboBox_2, self.comboBox_9)
        MUSCLE.setTabOrder(self.comboBox_9, self.pushButton)
        MUSCLE.setTabOrder(self.pushButton, self.pushButton_2)
        MUSCLE.setTabOrder(self.pushButton_2, self.pushButton_9)

    def retranslateUi(self, MUSCLE):
        _translate = QtCore.QCoreApplication.translate
        MUSCLE.setWindowTitle(_translate("MUSCLE", "MUSCLE"))
        self.groupBox_4.setTitle(_translate("MUSCLE", "Input"))
        self.label_4.setText(_translate("MUSCLE", "Input:"))
        self.label_9.setText(_translate("MUSCLE", "Auto-input from Extraction Results"))
        self.AA_radioButton_2.setToolTip(_translate("MUSCLE", "Amino acid sequences"))
        self.AA_radioButton_2.setText(_translate("MUSCLE", "AA"))
        self.PCG_radioButton_2.setToolTip(_translate("MUSCLE", "Protein-coding genes"))
        self.PCG_radioButton_2.setText(_translate("MUSCLE", "PCGs"))
        self.RNAs_radioButton_2.setToolTip(_translate("MUSCLE", "RNA sequences (rRNA and tRNA)"))
        self.RNAs_radioButton_2.setText(_translate("MUSCLE", "RNAs"))
        self.label_5.setText(_translate("MUSCLE", "<html><head/><body><p>Try to drag your <span style=\" font-weight:600; color:#ff0000;\">fasta</span> file and drop here</p></body></html>"))
        self.label_8.setText(_translate("MUSCLE", "Demo:"))
        self.label_7.setToolTip(_translate("MUSCLE", "Brief example"))
        self.groupBox_2.setTitle(_translate("MUSCLE", "Parameter"))
        self.label.setText(_translate("MUSCLE", "algorithm:"))
        self.comboBox_3.setItemText(0, _translate("MUSCLE", "align -- Align sequences using the PPP algorithm"))
        self.comboBox_3.setItemText(1, _translate("MUSCLE", "align-codon -- Align sequences using the PPP algorithm in codon mode"))
        self.comboBox_3.setItemText(2, _translate("MUSCLE", "super5 -- Align large datasets using the Super5 algorithm"))
        self.comboBox_3.setItemText(3, _translate("MUSCLE", "super5-codon -- Align large datasets using the Super5 algorithm in codon mode"))
        self.label_22.setText(_translate("MUSCLE", "Code Table:"))
        self.checkBox_3.setText(_translate("MUSCLE", "Number of replicates"))
        self.comboBox_9.setItemText(0, _translate("MUSCLE", "1 The standard code"))
        self.comboBox_9.setItemText(1, _translate("MUSCLE", "2 Vertebrate mitochondrial code"))
        self.comboBox_9.setItemText(2, _translate("MUSCLE", "3 The Yeast Mitochondrial Code"))
        self.comboBox_9.setItemText(3, _translate("MUSCLE", "4 Mold, Protozoan, and Coelenterate Mitochondrial code and Mycoplasma/Spiroplasma code"))
        self.comboBox_9.setItemText(4, _translate("MUSCLE", "5 Invertebrate mitochondrial"))
        self.comboBox_9.setItemText(5, _translate("MUSCLE", "6 The Ciliate, Dasycladacean and Hexamita Nuclear Code"))
        self.comboBox_9.setItemText(6, _translate("MUSCLE", "9 Echinoderm and Flatworm mitochondrial code"))
        self.comboBox_9.setItemText(7, _translate("MUSCLE", "10 The Euplotid Nuclear Code"))
        self.comboBox_9.setItemText(8, _translate("MUSCLE", "11 The Bacterial, Archaeal and Plant Plastid Code"))
        self.comboBox_9.setItemText(9, _translate("MUSCLE", "12 The Alternative Yeast Nuclear Code"))
        self.comboBox_9.setItemText(10, _translate("MUSCLE", "13 Ascidian mitochondrial code"))
        self.comboBox_9.setItemText(11, _translate("MUSCLE", "14 Alternative flatworm mitochondrial code"))
        self.comboBox_9.setItemText(12, _translate("MUSCLE", "16 Chlorophycean Mitochondrial Code"))
        self.comboBox_9.setItemText(13, _translate("MUSCLE", "21 Trematode Mitochondrial Code"))
        self.comboBox_9.setItemText(14, _translate("MUSCLE", "22 Scenedesmus obliquus Mitochondrial Code"))
        self.comboBox_9.setItemText(15, _translate("MUSCLE", "23 Thraustochytrium Mitochondrial Code"))
        self.comboBox_9.setItemText(16, _translate("MUSCLE", "24 Pterobranchia Mitochondrial Code"))
        self.comboBox_9.setItemText(17, _translate("MUSCLE", "25 Candidate Division SR1 and Gracilibacteria Code"))
        self.comboBox_9.setItemText(18, _translate("MUSCLE", "26 Pachysolen tannophilus Nuclear Code"))
        self.comboBox_9.setItemText(19, _translate("MUSCLE", "27 Karyorelict Nuclear"))
        self.comboBox_9.setItemText(20, _translate("MUSCLE", "28 Condylostoma Nuclear"))
        self.comboBox_9.setItemText(21, _translate("MUSCLE", "29 Mesodinium Nuclear"))
        self.comboBox_9.setItemText(22, _translate("MUSCLE", "30 Peritrich Nuclear"))
        self.comboBox_9.setItemText(23, _translate("MUSCLE", "31 Blastocrithidia Nuclear"))
        self.spinBox.setPrefix(_translate("MUSCLE", "Seed for HMM perturbations: "))
        self.checkBox_6.setText(_translate("MUSCLE", "perturb"))
        self.spinBox_2.setSuffix(_translate("MUSCLE", " (4 for -stratified; 100 for -diversified)"))
        self.checkBox_4.setText(_translate("MUSCLE", "consiters"))
        self.checkBox_5.setText(_translate("MUSCLE", "refineiters"))
        self.spinBox_3.setPrefix(_translate("MUSCLE", "Number of consistency iterations: "))
        self.spinBox_4.setPrefix(_translate("MUSCLE", "Number of refinement iterations: "))
        self.label_26.setToolTip(_translate("MUSCLE", "How many files to run simultaneously"))
        self.label_26.setText(_translate("MUSCLE", "Parallel files"))
        self.comboBox_6.setToolTip(_translate("MUSCLE", "How many files to run simultaneously"))
        self.checkBox_7.setText(_translate("MUSCLE", "perm (guide tree permutation)"))
        self.comboBox_2.setItemText(0, _translate("MUSCLE", "none"))
        self.comboBox_2.setItemText(1, _translate("MUSCLE", "abc"))
        self.comboBox_2.setItemText(2, _translate("MUSCLE", "acb"))
        self.comboBox_2.setItemText(3, _translate("MUSCLE", "bca"))
        self.label_25.setText(_translate("MUSCLE", "Threads per file"))
        self.checkBox.setText(_translate("MUSCLE", "Generate stratified ensemble"))
        self.checkBox_2.setText(_translate("MUSCLE", "Generate diversified ensemble"))
        self.groupBox_3.setTitle(_translate("MUSCLE", "Run"))
        self.pushButton.setText(_translate("MUSCLE", "Start"))
        self.pushButton_2.setText(_translate("MUSCLE", "Stop"))
        self.groupBox.setTitle(_translate("MUSCLE", "Progress"))
        self.label_3.setText(_translate("MUSCLE", "file:"))
        self.label_2.setText(_translate("MUSCLE", "Total:"))
        self.label_6.setText(_translate("MUSCLE", "Log:"))
        self.pushButton_9.setText(_translate("MUSCLE", "Show log"))

from src.CustomWidget import ArrowPushButton, ClickedLableGif, ListQCombobox

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MUSCLE = QtWidgets.QDialog()
    ui = Ui_MUSCLE()
    ui.setupUi(MUSCLE)
    MUSCLE.show()
    sys.exit(app.exec_())

