# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\HUAWEI\works\phylosuite\PhyloSuite_gitee\PhyloSuite\uifiles\MSA_view.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MSAview(object):
    def setupUi(self, MSAview):
        MSAview.setObjectName("MSAview")
        MSAview.resize(1000, 649)
        MSAview.setMinimumSize(QtCore.QSize(1000, 10))
        self.centralwidget = QtWidgets.QWidget(MSAview)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEdit_input = InputQLineEdit(self.centralwidget)
        self.lineEdit_input.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_input.setText("")
        self.lineEdit_input.setReadOnly(True)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.horizontalLayout.addWidget(self.lineEdit_input)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(30, 26))
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 26))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.lineEdit = ComLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout_2.addWidget(self.splitter)
        MSAview.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MSAview)
        self.statusbar.setObjectName("statusbar")
        MSAview.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MSAview)
        self.toolBar.setIconSize(QtCore.QSize(30, 30))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MSAview.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionUpdate_figure = QtWidgets.QAction(MSAview)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/resourses/refresh-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpdate_figure.setIcon(icon)
        self.actionUpdate_figure.setObjectName("actionUpdate_figure")
        self.actionFit_The_Window = QtWidgets.QAction(MSAview)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/seq_Viewer/resourses/seq_viewer/28105126-d6a6ce90-66fb-11e7-8546-72517772000b.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFit_The_Window.setIcon(icon1)
        self.actionFit_The_Window.setObjectName("actionFit_The_Window")
        self.actionPDF = QtWidgets.QAction(MSAview)
        self.actionPDF.setObjectName("actionPDF")
        self.actionJPG = QtWidgets.QAction(MSAview)
        self.actionJPG.setObjectName("actionJPG")
        self.actionsave_as = QtWidgets.QAction(MSAview)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/picture/resourses/Save-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsave_as.setIcon(icon2)
        self.actionsave_as.setObjectName("actionsave_as")
        self.actionsettings = QtWidgets.QAction(MSAview)
        self.actionsettings.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/picture/resourses/settings-icon-flat_343252.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsettings.setIcon(icon3)
        self.actionsettings.setObjectName("actionsettings")
        self.toolBar.addAction(self.actionUpdate_figure)
        self.toolBar.addAction(self.actionsave_as)
        self.toolBar.addAction(self.actionsettings)

        self.retranslateUi(MSAview)
        QtCore.QMetaObject.connectSlotsByName(MSAview)

    def retranslateUi(self, MSAview):
        _translate = QtCore.QCoreApplication.translate
        MSAview.setWindowTitle(_translate("MSAview", "Alignment viewer"))
        self.label_5.setText(_translate("MSAview", "Alignment File:"))
        self.lineEdit_input.setPlaceholderText(_translate("MSAview", "The file should be FASTA/NEXUS/PHYLIP format"))
        self.label_13.setText(_translate("MSAview", "Font:"))
        self.lineEdit.setText(_translate("MSAview", "Arial"))
        self.toolBar.setWindowTitle(_translate("MSAview", "toolBar"))
        self.actionUpdate_figure.setText(_translate("MSAview", "Update figure"))
        self.actionUpdate_figure.setToolTip(_translate("MSAview", "Update figure"))
        self.actionFit_The_Window.setText(_translate("MSAview", "Fit The Window"))
        self.actionPDF.setText(_translate("MSAview", "PDF"))
        self.actionJPG.setText(_translate("MSAview", "JPG"))
        self.actionsave_as.setText(_translate("MSAview", "save as"))
        self.actionsettings.setText(_translate("MSAview", "settings"))
        self.actionsettings.setToolTip(_translate("MSAview", "Show/Hide settings"))

from src.CustomWidget import ComLineEdit, InputQLineEdit
from uifiles import myRes_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MSAview = QtWidgets.QMainWindow()
    ui = Ui_MSAview()
    ui.setupUi(MSAview)
    MSAview.show()
    sys.exit(app.exec_())

