# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\works\ZD\phylosuite\uifiles\PF_exe_path.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PF2ExePath(object):
    def setupUi(self, PF2ExePath):
        PF2ExePath.setObjectName("PF2ExePath")
        PF2ExePath.resize(550, 539)
        PF2ExePath.setMinimumSize(QtCore.QSize(550, 0))
        PF2ExePath.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(PF2ExePath)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_5 = QtWidgets.QGroupBox(PF2ExePath)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setHorizontalSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 0, 1, 3)
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_3.setDragEnabled(True)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_4.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_5)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/resourses/btn_ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_5)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/picture/resourses/btn_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon1)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 2, 0, 1, 3)
        self.toolButton_5 = QtWidgets.QToolButton(self.groupBox_5)
        self.toolButton_5.setStyleSheet("")
        self.toolButton_5.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/picture/resourses/Open_folder_add_512px_1186192_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon2)
        self.toolButton_5.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_5.setCheckable(False)
        self.toolButton_5.setChecked(False)
        self.toolButton_5.setAutoRaise(True)
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout_4.addWidget(self.toolButton_5, 1, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.label_14 = QtWidgets.QLabel(PF2ExePath)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(PF2ExePath)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.comboBox = QtWidgets.QComboBox(PF2ExePath)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(PF2ExePath)
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/picture/resourses/Install.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setWordWrap(True)
        self.label_7.setOpenExternalLinks(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(PF2ExePath)
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setChecked(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_8.setIcon(icon3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setWordWrap(True)
        self.label_8.setOpenExternalLinks(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_4.addWidget(self.pushButton_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(PF2ExePath)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_9 = ClickedLableGif(PF2ExePath)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)

        self.retranslateUi(PF2ExePath)
        QtCore.QMetaObject.connectSlotsByName(PF2ExePath)

    def retranslateUi(self, PF2ExePath):
        _translate = QtCore.QCoreApplication.translate
        PF2ExePath.setWindowTitle(_translate("PF2ExePath", "Specify excutable path"))
        self.groupBox_5.setTitle(_translate("PF2ExePath", "Specify"))
        self.label_16.setText(_translate("PF2ExePath", "<html><head/><body><p>If you have a PartitionFinder2 (python script or excutable file), please <span style=\" font-weight:600; color:#ff0000;\">specify (folder)</span>.</p></body></html>"))
        self.label_17.setText(_translate("PF2ExePath", "PF2 Path:"))
        self.lineEdit_3.setPlaceholderText(_translate("PF2ExePath", "C:\\R-3.4.4\\bin\\Rscript.exe"))
        self.pushButton_9.setText(_translate("PF2ExePath", "Ok"))
        self.pushButton_10.setText(_translate("PF2ExePath", "Cancel"))
        self.label_14.setText(_translate("PF2ExePath", "<html><head/><body><p>If you don\'t have PartitionFinder2, please <span style=\" font-weight:600; color:#ff0000;\">download.</span> Please select one of the two ways to install PartitionFinder2 below:</p></body></html>"))
        self.label_10.setText(_translate("PF2ExePath", "Downloading source:"))
        self.comboBox.setItemText(0, _translate("PF2ExePath", "Chinese resource"))
        self.comboBox.setItemText(1, _translate("PF2ExePath", "Github"))
        self.comboBox.setItemText(2, _translate("PF2ExePath", "Gitlab"))
        self.groupBox_2.setTitle(_translate("PF2ExePath", "Install compiled PartitionFinder2 (recommended)"))
        self.pushButton_6.setText(_translate("PF2ExePath", "Download"))
        self.label_7.setText(_translate("PF2ExePath", "<html><head/><body><p>If you fail to download this, click here to download it manually.</p></body></html>"))
        self.label_18.setText(_translate("PF2ExePath", "This executable file was compiled by us, if it is not working, please select the option below."))
        self.groupBox_3.setTitle(_translate("PF2ExePath", "Install python 2.7 and PartitionFinder2"))
        self.groupBox_4.setTitle(_translate("PF2ExePath", "Download PartitionFinder2"))
        self.pushButton_8.setText(_translate("PF2ExePath", "Download"))
        self.label_8.setText(_translate("PF2ExePath", "<html><head/><body><p>If you fail to download this, click here to download it manually.</p></body></html>"))
        self.label_5.setText(_translate("PF2ExePath", "python 2.7:"))
        self.pushButton_11.setText(_translate("PF2ExePath", "Configure"))
        self.label_6.setText(_translate("PF2ExePath", "Don\'t know how to configure? Please see"))
        self.label_9.setToolTip(_translate("PF2ExePath", "Brief example"))

from src.CustomWidget import ClickedLableGif
from uifiles import myRes_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PF2ExePath = QtWidgets.QDialog()
    ui = Ui_PF2ExePath()
    ui.setupUi(PF2ExePath)
    PF2ExePath.show()
    sys.exit(app.exec_())

