# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\works\ZD\phylosuite\PhyloSuite\uifiles\RSCUfig.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RSCUfig(object):
    def setupUi(self, RSCUfig):
        RSCUfig.setObjectName("RSCUfig")
        RSCUfig.resize(488, 596)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(RSCUfig)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.splitter = QtWidgets.QSplitter(RSCUfig)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget_3 = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_3.setAcceptDrops(True)
        self.listWidget_3.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.listWidget_3.setDragEnabled(True)
        self.listWidget_3.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listWidget_3.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget_3.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_3.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridLayout.addWidget(self.listWidget_3, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.toolButton_T = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_T.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButton_T.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButton_T.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/resourses/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_T.setIcon(icon)
        self.toolButton_T.setIconSize(QtCore.QSize(26, 26))
        self.toolButton_T.setAutoRaise(True)
        self.toolButton_T.setObjectName("toolButton_T")
        self.verticalLayout_2.addWidget(self.toolButton_T)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setOpenExternalLinks(True)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout.addWidget(self.label_16)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_2 = ClickedLableGif(self.groupBox)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget_2.setDragEnabled(True)
        self.listWidget_2.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listWidget_2.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_3.addWidget(self.listWidget_2)
        self.gridLayout_6.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 169, 209))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_color = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_color.sizePolicy().hasHeightForWidth())
        self.pushButton_color.setSizePolicy(sizePolicy)
        self.pushButton_color.setAutoFillBackground(False)
        self.pushButton_color.setStyleSheet("")
        self.pushButton_color.setText("")
        self.pushButton_color.setObjectName("pushButton_color")
        self.verticalLayout.addWidget(self.pushButton_color)
        self.pushButton_color_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_color_2.sizePolicy().hasHeightForWidth())
        self.pushButton_color_2.setSizePolicy(sizePolicy)
        self.pushButton_color_2.setAutoFillBackground(False)
        self.pushButton_color_2.setStyleSheet("")
        self.pushButton_color_2.setText("")
        self.pushButton_color_2.setObjectName("pushButton_color_2")
        self.verticalLayout.addWidget(self.pushButton_color_2)
        self.pushButton_color_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_color_3.sizePolicy().hasHeightForWidth())
        self.pushButton_color_3.setSizePolicy(sizePolicy)
        self.pushButton_color_3.setAutoFillBackground(False)
        self.pushButton_color_3.setStyleSheet("")
        self.pushButton_color_3.setText("")
        self.pushButton_color_3.setObjectName("pushButton_color_3")
        self.verticalLayout.addWidget(self.pushButton_color_3)
        self.pushButton_color_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_color_4.sizePolicy().hasHeightForWidth())
        self.pushButton_color_4.setSizePolicy(sizePolicy)
        self.pushButton_color_4.setAutoFillBackground(False)
        self.pushButton_color_4.setStyleSheet("")
        self.pushButton_color_4.setText("")
        self.pushButton_color_4.setObjectName("pushButton_color_4")
        self.verticalLayout.addWidget(self.pushButton_color_4)
        self.pushButton_color_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_color_5.sizePolicy().hasHeightForWidth())
        self.pushButton_color_5.setSizePolicy(sizePolicy)
        self.pushButton_color_5.setAutoFillBackground(False)
        self.pushButton_color_5.setStyleSheet("")
        self.pushButton_color_5.setText("")
        self.pushButton_color_5.setObjectName("pushButton_color_5")
        self.verticalLayout.addWidget(self.pushButton_color_5)
        self.pushButton_color_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_color_6.sizePolicy().hasHeightForWidth())
        self.pushButton_color_6.setSizePolicy(sizePolicy)
        self.pushButton_color_6.setAutoFillBackground(False)
        self.pushButton_color_6.setStyleSheet("")
        self.pushButton_color_6.setText("")
        self.pushButton_color_6.setObjectName("pushButton_color_6")
        self.verticalLayout.addWidget(self.pushButton_color_6)
        self.pushButton_color_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_color_7.sizePolicy().hasHeightForWidth())
        self.pushButton_color_7.setSizePolicy(sizePolicy)
        self.pushButton_color_7.setAutoFillBackground(False)
        self.pushButton_color_7.setStyleSheet("")
        self.pushButton_color_7.setText("")
        self.pushButton_color_7.setObjectName("pushButton_color_7")
        self.verticalLayout.addWidget(self.pushButton_color_7)
        self.pushButton_color_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_color_8.sizePolicy().hasHeightForWidth())
        self.pushButton_color_8.setSizePolicy(sizePolicy)
        self.pushButton_color_8.setAutoFillBackground(False)
        self.pushButton_color_8.setStyleSheet("")
        self.pushButton_color_8.setText("")
        self.pushButton_color_8.setObjectName("pushButton_color_8")
        self.verticalLayout.addWidget(self.pushButton_color_8)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.gridLayout_6.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.doubleSpinBox_2 = MyDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_2.setReadOnly(False)
        self.doubleSpinBox_2.setDecimals(1)
        self.doubleSpinBox_2.setSingleStep(0.1)
        self.doubleSpinBox_2.setProperty("value", 2.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 1, 0, 1, 2)
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_2)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 3, 1, 1)
        self.spinBox_8 = QtWidgets.QSpinBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_8.sizePolicy().hasHeightForWidth())
        self.spinBox_8.setSizePolicy(sizePolicy)
        self.spinBox_8.setMinimum(1)
        self.spinBox_8.setMaximum(999999999)
        self.spinBox_8.setProperty("value", 900)
        self.spinBox_8.setObjectName("spinBox_8")
        self.gridLayout_2.addWidget(self.spinBox_8, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 2)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox.setDecimals(3)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setProperty("value", 0.07)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_2.addWidget(self.doubleSpinBox, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 3, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_4.setDecimals(2)
        self.doubleSpinBox_4.setMaximum(10.0)
        self.doubleSpinBox_4.setSingleStep(0.1)
        self.doubleSpinBox_4.setProperty("value", 0.8)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_2.addWidget(self.doubleSpinBox_4, 1, 4, 1, 1)
        self.spinBox_7 = QtWidgets.QSpinBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_7.sizePolicy().hasHeightForWidth())
        self.spinBox_7.setSizePolicy(sizePolicy)
        self.spinBox_7.setMinimum(1)
        self.spinBox_7.setMaximum(999999999)
        self.spinBox_7.setSingleStep(10)
        self.spinBox_7.setProperty("value", 1000)
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout_2.addWidget(self.spinBox_7, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 2)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.lineEdit = ComLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.lineEdit_2 = ComLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.tab)
        self.doubleSpinBox_5.setDecimals(2)
        self.doubleSpinBox_5.setMaximum(10.0)
        self.doubleSpinBox_5.setSingleStep(0.1)
        self.doubleSpinBox_5.setProperty("value", 0.9)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_5.sizePolicy().hasHeightForWidth())
        self.spinBox_5.setSizePolicy(sizePolicy)
        self.spinBox_5.setMinimum(1)
        self.spinBox_5.setMaximum(999)
        self.spinBox_5.setProperty("value", 9)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout_3.addWidget(self.spinBox_5, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 0, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_6.sizePolicy().hasHeightForWidth())
        self.spinBox_6.setSizePolicy(sizePolicy)
        self.spinBox_6.setMinimum(1)
        self.spinBox_6.setMaximum(999)
        self.spinBox_6.setProperty("value", 8)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout_3.addWidget(self.spinBox_6, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 0, 1, 1)
        self.doubleSpinBox_3 = MyDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_3.setToolTip("")
        self.doubleSpinBox_3.setReadOnly(False)
        self.doubleSpinBox_3.setDecimals(1)
        self.doubleSpinBox_3.setSingleStep(0.1)
        self.doubleSpinBox_3.setProperty("value", 6.5)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_3.addWidget(self.doubleSpinBox_3, 2, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_6.addWidget(self.tabWidget, 2, 0, 1, 2)
        self.verticalLayout_7.addWidget(self.splitter)
        self.groupBox_3 = QtWidgets.QGroupBox(RSCUfig)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton = ArrowPushButton(self.groupBox_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/picture/resourses/if_start_60207.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/picture/resourses/if_Delete_1493279.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_5.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(RSCUfig)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_5)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_5)

        self.retranslateUi(RSCUfig)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RSCUfig)

    def retranslateUi(self, RSCUfig):
        _translate = QtCore.QCoreApplication.translate
        RSCUfig.setWindowTitle(_translate("RSCUfig", "Draw RSCU Figure"))
        self.groupBox.setTitle(_translate("RSCUfig", "Input"))
        self.listWidget_3.setToolTip(_translate("RSCUfig", "Try to drag to reorder"))
        self.toolButton_T.setShortcut(_translate("RSCUfig", "Del"))
        self.label_16.setText(_translate("RSCUfig", "<html><head/><body><p>Try to drag <span style=\" font-weight:600; color:#ff0105;\">RSCU</span> tables (<span style=\" color:#ff0000;\">*</span><span style=\" font-weight:600; color:#ff0000;\">_stack.csv</span>) and drop here</p></body></html>"))
        self.label_3.setText(_translate("RSCUfig", "Demo:"))
        self.label_2.setToolTip(_translate("RSCUfig", "Brief example"))
        self.label_12.setText(_translate("RSCUfig", "<html><head/><body><p><span style=\" color:#ff0000;\">Note that only files that are extracted by PhyloSuite v1.2.3 or higher are allowed</span></p></body></html>"))
        self.groupBox_2.setTitle(_translate("RSCUfig", "Parameters"))
        self.label_4.setText(_translate("RSCUfig", "Order on the x-axis:"))
        self.listWidget_2.setToolTip(_translate("RSCUfig", "Try to drag to reorder"))
        self.label_6.setText(_translate("RSCUfig", "Color of stacks:"))
        self.pushButton_color.setToolTip(_translate("RSCUfig", "Click to change color"))
        self.pushButton_color_2.setToolTip(_translate("RSCUfig", "Click to change color"))
        self.pushButton_color_3.setToolTip(_translate("RSCUfig", "Click to change color"))
        self.pushButton_color_4.setToolTip(_translate("RSCUfig", "Click to change color"))
        self.pushButton_color_5.setToolTip(_translate("RSCUfig", "Click to change color"))
        self.pushButton_color_6.setToolTip(_translate("RSCUfig", "Click to change color"))
        self.pushButton_color_7.setToolTip(_translate("RSCUfig", "Click to change color"))
        self.pushButton_color_8.setToolTip(_translate("RSCUfig", "Click to change color"))
        self.label_13.setText(_translate("RSCUfig", "Adjust height ratio of RSCU figure to bottom legend:"))
        self.doubleSpinBox_2.setToolTip(_translate("RSCUfig", "the input must be multiple of 0.5"))
        self.label_17.setText(_translate("RSCUfig", "Figure width:"))
        self.label.setText(_translate("RSCUfig", "Figure interval:"))
        self.label_5.setText(_translate("RSCUfig", "RSCU offset:"))
        self.label_10.setText(_translate("RSCUfig", "Figure height:"))
        self.label_7.setText(_translate("RSCUfig", "Font:"))
        self.lineEdit.setText(_translate("RSCUfig", "Arial"))
        self.label_8.setText(_translate("RSCUfig", "Size:"))
        self.lineEdit_2.setText(_translate("RSCUfig", "13"))
        self.label_11.setText(_translate("RSCUfig", "Bar width:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("RSCUfig", "Plotly (Python)"))
        self.label_9.setText(_translate("RSCUfig", "Figure height:"))
        self.label_15.setText(_translate("RSCUfig", "Figure width:"))
        self.label_14.setText(_translate("RSCUfig", "Maximum value of y-axis:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("RSCUfig", "ggplot (R)"))
        self.groupBox_3.setTitle(_translate("RSCUfig", "Run"))
        self.pushButton.setText(_translate("RSCUfig", "Start"))
        self.pushButton_2.setText(_translate("RSCUfig", "Close"))
        self.groupBox_5.setTitle(_translate("RSCUfig", "Progress"))

from src.CustomWidget import ArrowPushButton, ClickedLableGif, ComLineEdit, MyDoubleSpinBox
from uifiles import myRes_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RSCUfig = QtWidgets.QDialog()
    ui = Ui_RSCUfig()
    ui.setupUi(RSCUfig)
    RSCUfig.show()
    sys.exit(app.exec_())

