# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\works\ZD\phylosuite\PhyloSuite\uifiles\settings.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.setWindowModality(QtCore.Qt.NonModal)
        Settings.resize(703, 393)
        Settings.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.gridLayout_3 = QtWidgets.QGridLayout(Settings)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(Settings)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.listWidget = QtWidgets.QListWidget(self.splitter)
        self.listWidget.setObjectName("listWidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.splitter)
        self.stackedWidget.setStyleSheet("QStackedWidget {background-color: white}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidget = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(16)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 2, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.gridLayout_5.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_container_2 = QtWidgets.QWidget(self.page_3)
        self.widget_container_2.setStyleSheet("QWidget#widget_container_2 {border: 1px ridge gray; background-color: white}")
        self.widget_container_2.setObjectName("widget_container_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_container_2)
        self.gridLayout_6.setContentsMargins(5, 3, 5, 3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tableView_2 = QtWidgets.QTableView(self.widget_container_2)
        self.tableView_2.setAcceptDrops(True)
        self.tableView_2.setDragEnabled(True)
        self.tableView_2.setDragDropOverwriteMode(True)
        self.tableView_2.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.tableView_2.setDefaultDropAction(QtCore.Qt.TargetMoveAction)
        self.tableView_2.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableView_2.setObjectName("tableView_2")
        self.tableView_2.horizontalHeader().setSortIndicatorShown(True)
        self.tableView_2.horizontalHeader().setStretchLastSection(False)
        self.gridLayout_6.addWidget(self.tableView_2, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_container_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/resourses/table_row_add_after.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_container_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/picture/resourses/table_column_add_after.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        self.label_6 = ClickedLableGif(self.widget_container_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_container_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/picture/resourses/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 1, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_container_2)
        self.pushButton_9.setIcon(icon2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.widget_container_2)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.toolButton_3 = QtWidgets.QToolButton(self.widget_container_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/picture/resourses/add-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon3)
        self.toolButton_3.setAutoRaise(True)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_3.addWidget(self.toolButton_3)
        self.toolButton_4 = QtWidgets.QToolButton(self.widget_container_2)
        self.toolButton_4.setIcon(icon2)
        self.toolButton_4.setAutoRaise(True)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout_3.addWidget(self.toolButton_4)
        self.line = QtWidgets.QFrame(self.widget_container_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.toolButton_6 = QtWidgets.QToolButton(self.widget_container_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/picture/resourses/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_6.setIcon(icon4)
        self.toolButton_6.setAutoRaise(True)
        self.toolButton_6.setObjectName("toolButton_6")
        self.horizontalLayout_3.addWidget(self.toolButton_6)
        self.toolButton_5 = QtWidgets.QToolButton(self.widget_container_2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/picture/resourses/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon5)
        self.toolButton_5.setAutoRaise(True)
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout_3.addWidget(self.toolButton_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_container_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_container = QtWidgets.QWidget(self.page)
        self.widget_container.setStyleSheet("QWidget#widget_container {border: 1px ridge gray; background-color: white}")
        self.widget_container.setObjectName("widget_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_container)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.widget_3 = QtWidgets.QWidget(self.widget_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setStyleSheet("border-top: 1px solid gray;\n"
"margin-top: 5px;")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout.addWidget(self.widget_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.widget_container)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.lineEdit = ComLineEdit(self.widget_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.label_4 = QtWidgets.QLabel(self.widget_container)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_2 = ComLineEdit(self.widget_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton = QtWidgets.QPushButton(self.widget_container)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.pushButton, 0, 0, 1, 2)
        self.pushButton_export = QtWidgets.QPushButton(self.widget_container)
        self.pushButton_export.setIcon(icon5)
        self.pushButton_export.setObjectName("pushButton_export")
        self.gridLayout_7.addWidget(self.pushButton_export, 1, 0, 1, 1)
        self.pushButton_import = QtWidgets.QPushButton(self.widget_container)
        self.pushButton_import.setIcon(icon4)
        self.pushButton_import.setObjectName("pushButton_import")
        self.gridLayout_7.addWidget(self.pushButton_import, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.widget_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.widget_2 = QtWidgets.QWidget(self.widget_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("border-top: 1px solid gray;\n"
"margin-top: 5px;")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4.addWidget(self.widget_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.widget_container)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget_container)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget_container)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget_container)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget_container)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout.addWidget(self.checkBox_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 304, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout.addWidget(self.widget_container, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(Settings)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Settings", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Settings", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Settings", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Settings", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Settings", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Settings", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Settings", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Settings", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Settings", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Settings", "10"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Settings", "11"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Settings", "12"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Settings", "13"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Settings", "14"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Settings", "15"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("Settings", "16"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Settings", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Settings", "Description"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Settings", "Status"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Settings", "Operation"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Settings", "MAFFT"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Settings", "Mafft mutiple aligner"))
        item.setToolTip(_translate("Settings", "Mafft mutiple aligner"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Settings", "Uninstalled"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Settings", "Rscript"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Settings", "Scripting Front-End For R"))
        item.setToolTip(_translate("Settings", "Scripting Front-End For R"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("Settings", "Uninstalled"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Settings", "Python 2.7 + PartitionFinder2"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Settings", "Python 2.7: Using for PartitionFinder"))
        item.setToolTip(_translate("Settings", "Using for PartitionFinder"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("Settings", "Uninstalled"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Settings", "PartitionFinder2"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Settings", "PartitionFinder2: Python 2.7Selecting best-fit partitioning schemes and models of molecular evolution for phylogenetic analyses"))
        item.setToolTip(_translate("Settings", "Selecting best-fit partitioning schemes and models of molecular evolution for phylogenetic analyses"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("Settings", "Uninstalled"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Settings", "Gblocks"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("Settings", "Selection of conserved blocks from multiple alignments for their use in phylogenetic analysis"))
        item.setToolTip(_translate("Settings", "Selection of conserved blocks from multiple alignments for their use in phylogenetic analysis"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("Settings", "Uninstalled"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Settings", "IQ-TREE"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("Settings", "Efficient software for phylogenomic inference"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("Settings", "Uninstalled"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("Settings", "MrBayes"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("Settings", "A free software program which performs Bayesian inference of phylogeny."))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("Settings", "Uninstalled"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("Settings", "tbl2asn"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("Settings", "Automates the creation of sequence records for submission to GenBank"))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("Settings", "Uninstalled"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("Settings", "MPICH2"))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("Settings", "A high-performance and widely portable implementation of the Message Passing Interface (MPI) standard"))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("Settings", "Uninstalled"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("Settings", "JAVA (JRE>1.5) + MACSE"))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("Settings", "JAVA: Using for MACSE"))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("Settings", "Uninstalled"))
        item = self.tableWidget.item(10, 1)
        item.setText(_translate("Settings", "MACSE: Multiple Alignment of Coding SEquences Accounting for Frameshifts and Stop Codons."))
        item = self.tableWidget.item(10, 2)
        item.setText(_translate("Settings", "Uninstalled"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("Settings", "trimAl"))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("Settings", "trimAl: a tool for automated alignment trimming"))
        item = self.tableWidget.item(11, 2)
        item.setText(_translate("Settings", "Uninstalled"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("Settings", "Perl 5 +         HmmCleaner"))
        item = self.tableWidget.item(12, 1)
        item.setText(_translate("Settings", "Perl 5: Using for HmmCleaner"))
        item = self.tableWidget.item(12, 2)
        item.setText(_translate("Settings", "Uninstalled"))
        item = self.tableWidget.item(13, 1)
        item.setText(_translate("Settings", "HmmCleaner: Removing low similarity segments from your MSA"))
        item = self.tableWidget.item(13, 2)
        item.setText(_translate("Settings", "Uninstalled"))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("Settings", "CodonW"))
        item = self.tableWidget.item(14, 1)
        item.setText(_translate("Settings", "Correspondence Analysis of Codon Usage"))
        item = self.tableWidget.item(14, 2)
        item.setText(_translate("Settings", "Uninstalled"))
        item = self.tableWidget.item(15, 0)
        item.setText(_translate("Settings", "Plot engine"))
        item = self.tableWidget.item(15, 1)
        item.setText(_translate("Settings", "Plot engine for PhyloSuite"))
        item = self.tableWidget.item(15, 2)
        item.setText(_translate("Settings", "Uninstalled"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_6.setText(_translate("Settings", "Add Row"))
        self.pushButton_7.setText(_translate("Settings", "Add Column"))
        self.label_6.setToolTip(_translate("Settings", "Brief example"))
        self.pushButton_8.setText(_translate("Settings", "Delete Row"))
        self.pushButton_9.setText(_translate("Settings", "Delete Column"))
        self.toolButton_3.setToolTip(_translate("Settings", "Add"))
        self.toolButton_3.setText(_translate("Settings", "..."))
        self.toolButton_4.setToolTip(_translate("Settings", "Delete"))
        self.toolButton_4.setText(_translate("Settings", "..."))
        self.toolButton_6.setToolTip(_translate("Settings", "Import settings"))
        self.toolButton_6.setText(_translate("Settings", "..."))
        self.toolButton_5.setToolTip(_translate("Settings", "Export settings"))
        self.toolButton_5.setText(_translate("Settings", "..."))
        self.label_2.setText(_translate("Settings", "General"))
        self.label_3.setText(_translate("Settings", "Font:"))
        self.lineEdit.setText(_translate("Settings", "Arial"))
        self.label_4.setText(_translate("Settings", "Size:"))
        self.lineEdit_2.setText(_translate("Settings", "10"))
        self.pushButton.setText(_translate("Settings", "Restore default settings"))
        self.pushButton_export.setText(_translate("Settings", "Export settings"))
        self.pushButton_import.setText(_translate("Settings", "Import settings"))
        self.label.setText(_translate("Settings", "Reminder settings"))
        self.checkBox.setText(_translate("Settings", "Show the \'Previous results will be overwritten\' warning"))
        self.checkBox_2.setText(_translate("Settings", "Show the \'Settings are saved automatically\' notification"))
        self.checkBox_3.setText(_translate("Settings", "Check updates when opening PhyloSuite"))
        self.checkBox_4.setText(_translate("Settings", "Popup auto-prepared inputs for functions"))
        self.checkBox_5.setText(_translate("Settings", "Popup workplace selection when opening PhyloSuite"))

from src.CustomWidget import ClickedLableGif, ComLineEdit
from uifiles import myRes_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QDialog()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())

