# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\works\ZD\phylosuite\uifiles\trimAl.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_trimAl(object):
    def setupUi(self, trimAl):
        trimAl.setObjectName("trimAl")
        trimAl.resize(879, 552)
        trimAl.setStyleSheet("")
        trimAl.setSizeGripEnabled(True)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(trimAl)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(trimAl)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.comboBox_4 = ListQCombobox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setAcceptDrops(True)
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_5.addWidget(self.comboBox_4, 0, 1, 1, 2)
        self.lineEdit_3 = InputQLineEdit(self.groupBox_4)
        self.lineEdit_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_5.addWidget(self.lineEdit_3, 2, 1, 1, 2)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_5.addWidget(self.radioButton, 0, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_5.addWidget(self.radioButton_2, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 2, 0, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_22.sizePolicy().hasHeightForWidth())
        self.pushButton_22.setSizePolicy(sizePolicy)
        self.pushButton_22.setMinimumSize(QtCore.QSize(30, 26))
        self.pushButton_22.setMaximumSize(QtCore.QSize(30, 26))
        self.pushButton_22.setStyleSheet("")
        self.pushButton_22.setText("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_5.addWidget(self.pushButton_22, 2, 3, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_5.addWidget(self.label_40, 3, 0, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout_5.addWidget(self.comboBox_6, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 3, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_5.addWidget(self.pushButton_3, 0, 3, 1, 1)
        self.label_7 = ClickedLableGif(self.groupBox_4)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 3, 3, 1, 1)
        self.lineEdit_2 = InputQLineEdit(self.groupBox_4)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_5.addWidget(self.lineEdit_2, 1, 1, 1, 2)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(30, 26))
        self.pushButton_4.setMaximumSize(QtCore.QSize(30, 26))
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_5.addWidget(self.pushButton_4, 1, 3, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(trimAl)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setContentsMargins(3, 6, 3, 3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_2)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.radioButton_11 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_11.setObjectName("radioButton_11")
        self.gridLayout_8.addWidget(self.radioButton_11, 0, 1, 1, 1)
        self.radioButton_10 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_10.setChecked(True)
        self.radioButton_10.setObjectName("radioButton_10")
        self.gridLayout_8.addWidget(self.radioButton_10, 0, 0, 1, 1)
        self.radioButton_12 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_12.setObjectName("radioButton_12")
        self.gridLayout_8.addWidget(self.radioButton_12, 0, 2, 1, 1)
        self.radioButton_14 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_14.setObjectName("radioButton_14")
        self.gridLayout_8.addWidget(self.radioButton_14, 1, 1, 1, 1)
        self.radioButton_13 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_13.setObjectName("radioButton_13")
        self.gridLayout_8.addWidget(self.radioButton_13, 1, 0, 1, 1)
        self.radioButton_15 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_15.setObjectName("radioButton_15")
        self.gridLayout_8.addWidget(self.radioButton_15, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_8)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -69, 830, 162))
        self.scrollAreaWidgetContents.setStyleSheet("QWidget#scrollAreaWidgetContents {border: none; background-color: white}\n"
"")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox.setSizePolicy(sizePolicy)
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setProperty("value", 10.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_4.addWidget(self.doubleSpinBox, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_2.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_2.setSizePolicy(sizePolicy)
        self.doubleSpinBox_2.setDecimals(1)
        self.doubleSpinBox_2.setMaximum(1.0)
        self.doubleSpinBox_2.setSingleStep(0.1)
        self.doubleSpinBox_2.setProperty("value", 0.9)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_4.addWidget(self.doubleSpinBox_2, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setMinimumSize(QtCore.QSize(480, 0))
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_3.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_3.setSizePolicy(sizePolicy)
        self.doubleSpinBox_3.setDecimals(1)
        self.doubleSpinBox_3.setMaximum(1.0)
        self.doubleSpinBox_3.setSingleStep(0.1)
        self.doubleSpinBox_3.setProperty("value", 0.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_4.addWidget(self.doubleSpinBox_3, 2, 1, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_4.addWidget(self.checkBox_9, 3, 0, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_4.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_4.setSizePolicy(sizePolicy)
        self.doubleSpinBox_4.setDecimals(1)
        self.doubleSpinBox_4.setMaximum(1.0)
        self.doubleSpinBox_4.setSingleStep(0.1)
        self.doubleSpinBox_4.setProperty("value", 0.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_4.addWidget(self.doubleSpinBox_4, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setMinimumSize(QtCore.QSize(283, 0))
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_6.addWidget(self.checkBox_3, 0, 0, 1, 1)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_7.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_7.setSizePolicy(sizePolicy)
        self.doubleSpinBox_7.setMaximumSize(QtCore.QSize(55, 16777215))
        self.doubleSpinBox_7.setDecimals(1)
        self.doubleSpinBox_7.setMaximum(1e+21)
        self.doubleSpinBox_7.setSingleStep(0.1)
        self.doubleSpinBox_7.setProperty("value", 1.0)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.gridLayout_6.addWidget(self.doubleSpinBox_7, 0, 1, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_7.sizePolicy().hasHeightForWidth())
        self.checkBox_7.setSizePolicy(sizePolicy)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_6.addWidget(self.checkBox_7, 1, 0, 1, 1)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_5.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_5.setSizePolicy(sizePolicy)
        self.doubleSpinBox_5.setMaximumSize(QtCore.QSize(55, 16777215))
        self.doubleSpinBox_5.setDecimals(1)
        self.doubleSpinBox_5.setMaximum(1e+21)
        self.doubleSpinBox_5.setSingleStep(0.1)
        self.doubleSpinBox_5.setProperty("value", 1.0)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout_6.addWidget(self.doubleSpinBox_5, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_6)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.checkBox_6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_6.sizePolicy().hasHeightForWidth())
        self.checkBox_6.setSizePolicy(sizePolicy)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_9.addWidget(self.checkBox_6, 0, 0, 1, 1)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_6.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_6.setSizePolicy(sizePolicy)
        self.doubleSpinBox_6.setMaximumSize(QtCore.QSize(55, 16777215))
        self.doubleSpinBox_6.setDecimals(1)
        self.doubleSpinBox_6.setMaximum(1e+21)
        self.doubleSpinBox_6.setSingleStep(0.1)
        self.doubleSpinBox_6.setProperty("value", 1.0)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout_9.addWidget(self.doubleSpinBox_6, 0, 1, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_8.sizePolicy().hasHeightForWidth())
        self.checkBox_8.setSizePolicy(sizePolicy)
        self.checkBox_8.setMinimumSize(QtCore.QSize(240, 0))
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_9.addWidget(self.checkBox_8, 1, 0, 1, 1)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_8.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_8.setSizePolicy(sizePolicy)
        self.doubleSpinBox_8.setMaximumSize(QtCore.QSize(55, 16777215))
        self.doubleSpinBox_8.setDecimals(1)
        self.doubleSpinBox_8.setMaximum(1e+21)
        self.doubleSpinBox_8.setSingleStep(0.1)
        self.doubleSpinBox_8.setProperty("value", 1.0)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.gridLayout_9.addWidget(self.doubleSpinBox_8, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_7.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_7 = QtWidgets.QGroupBox(trimAl)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_15 = QtWidgets.QLabel(self.groupBox_7)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 0, 1, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_2.addWidget(self.checkBox_4, 0, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 0, 3, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_10.setChecked(True)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_2.addWidget(self.checkBox_10, 0, 4, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 0, 5, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_5.setChecked(False)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_2.addWidget(self.checkBox_5, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 1, 1, 1, 4)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 1, 5, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        self.groupBox_3 = QtWidgets.QGroupBox(trimAl)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/resourses/if_Delete_1493279.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton = ArrowPushButton(self.groupBox_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/picture/resourses/if_start_60207.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(trimAl)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 0, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/picture/resourses/Eye_Care_Services-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox)

        self.retranslateUi(trimAl)
        self.comboBox_6.setCurrentIndex(-1)
        self.tabWidget.setCurrentIndex(0)
        self.checkBox_4.toggled['bool'].connect(self.lineEdit_4.setEnabled)
        self.checkBox_5.toggled['bool'].connect(self.comboBox_2.setEnabled)
        self.radioButton.toggled['bool'].connect(self.comboBox_4.setEnabled)
        self.radioButton_2.toggled['bool'].connect(self.lineEdit_2.setEnabled)
        self.checkBox_9.toggled['bool'].connect(self.doubleSpinBox_4.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(trimAl)
        trimAl.setTabOrder(self.pushButton_3, self.comboBox_4)
        trimAl.setTabOrder(self.comboBox_4, self.pushButton)
        trimAl.setTabOrder(self.pushButton, self.pushButton_2)
        trimAl.setTabOrder(self.pushButton_2, self.pushButton_9)

    def retranslateUi(self, trimAl):
        _translate = QtCore.QCoreApplication.translate
        trimAl.setWindowTitle(_translate("trimAl", "trimAl"))
        self.groupBox_4.setTitle(_translate("trimAl", "Input"))
        self.lineEdit_3.setPlaceholderText(_translate("trimAl", "(Optional!) User-defined similarity matrix (default is Blosum62)"))
        self.radioButton.setText(_translate("trimAl", "Input:"))
        self.radioButton_2.setText(_translate("trimAl", "Compare set:"))
        self.label_18.setText(_translate("trimAl", "Matrix:"))
        self.label_40.setToolTip(_translate("trimAl", "Amino acid score matrix to use"))
        self.label_40.setText(_translate("trimAl", "Thread:"))
        self.comboBox_6.setToolTip(_translate("trimAl", "Amino acid score matrix to use"))
        self.label_5.setText(_translate("trimAl", "<html><head/><body><p>Click <a href=\"http://trimal.cgenomics.org/trimal\"><span style=\" text-decoration: underline; color:#0000ff;\">here</span></a> to learn more about trimAl.</p></body></html>"))
        self.label_7.setToolTip(_translate("trimAl", "Brief example"))
        self.lineEdit_2.setPlaceholderText(_translate("trimAl", "Files containing the alignments to compare"))
        self.groupBox_2.setTitle(_translate("trimAl", "Parameter"))
        self.radioButton_11.setToolTip(_translate("trimAl", "Remove all positions with gaps in the alignment.     "))
        self.radioButton_11.setText(_translate("trimAl", "nogaps"))
        self.radioButton_10.setToolTip(_translate("trimAl", "Use a heuristic selection of the automatic method based on similarity statistics.     "))
        self.radioButton_10.setText(_translate("trimAl", "automated1"))
        self.radioButton_12.setToolTip(_translate("trimAl", "Remove columns composed only by gaps."))
        self.radioButton_12.setText(_translate("trimAl", "noallgaps"))
        self.radioButton_14.setToolTip(_translate("trimAl", "Use automatic selection on \"strict\" mode."))
        self.radioButton_14.setText(_translate("trimAl", "strict"))
        self.radioButton_13.setToolTip(_translate("trimAl", "Use automatic selection on \"gappyout\" mode. This method only uses information based on"))
        self.radioButton_13.setText(_translate("trimAl", "gappyout"))
        self.radioButton_15.setToolTip(_translate("trimAl", "Use automatic selection on \"strictplus\" mode."))
        self.radioButton_15.setText(_translate("trimAl", "strictplus"))
        self.label_3.setText(_translate("trimAl", "Tips: Hover mouse over each checkbox to see the explanation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("trimAl", "Automated Trimming"))
        self.label.setToolTip(_translate("trimAl", "Minimum percentage of positions to conserve [0-100]"))
        self.label.setText(_translate("trimAl", "Minimum percentage of positions to conserve [0-100]:"))
        self.label_8.setToolTip(_translate("trimAl", "Gap threshold, fraction of positions without gaps in a column [0-1]"))
        self.label_8.setText(_translate("trimAl", "Gap threshold, fraction of positions without gaps in a column [0-1]:"))
        self.label_9.setToolTip(_translate("trimAl", "Similarity threshold, minimum level of residue similarity within a column [0-1]"))
        self.label_9.setText(_translate("trimAl", "Similarity threshold, minimum level of residue similarity within a column [0-1]:"))
        self.checkBox_9.setToolTip(_translate("trimAl", "consistency threshold, minimum consistency value required [0-1]"))
        self.checkBox_9.setText(_translate("trimAl", "consistency threshold, minimum consistency value required [0-1]:"))
        self.checkBox_3.setToolTip(_translate("trimAl", "General window size, applied to all stats"))
        self.checkBox_3.setText(_translate("trimAl", "General window size, applied to all stats:"))
        self.checkBox_7.setToolTip(_translate("trimAl", "Window size applied to Similarity"))
        self.checkBox_7.setText(_translate("trimAl", "Window size applied to Similarity:"))
        self.checkBox_6.setToolTip(_translate("trimAl", "Window size applied to Gaps"))
        self.checkBox_6.setText(_translate("trimAl", "Window size applied to Gaps:"))
        self.checkBox_8.setToolTip(_translate("trimAl", "Window size applied to Consistency"))
        self.checkBox_8.setText(_translate("trimAl", "Window size applied to Consistency:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("trimAl", "Manual Trimming"))
        self.groupBox_7.setTitle(_translate("trimAl", "Output"))
        self.label_15.setText(_translate("trimAl", "Output formats:"))
        self.comboBox.setItemText(0, _translate("trimAl", "fasta"))
        self.comboBox.setItemText(1, _translate("trimAl", "phylip"))
        self.comboBox.setItemText(2, _translate("trimAl", "phylip3.2"))
        self.comboBox.setItemText(3, _translate("trimAl", "nexus"))
        self.comboBox.setItemText(4, _translate("trimAl", "mega"))
        self.comboBox.setItemText(5, _translate("trimAl", "clustal"))
        self.comboBox.setItemText(6, _translate("trimAl", "nbrf"))
        self.checkBox_4.setText(_translate("trimAl", "htmlout:"))
        self.lineEdit_4.setText(_translate("trimAl", "summary.html"))
        self.checkBox_10.setToolTip(_translate("trimAl", "not trim sequence name"))
        self.checkBox_10.setText(_translate("trimAl", "Keep seq. name"))
        self.checkBox.setText(_translate("trimAl", "complementary"))
        self.checkBox_5.setText(_translate("trimAl", "Statistics output:"))
        self.comboBox_2.setItemText(0, _translate("trimAl", "sgc: Print gap percentage count for columns in the input alignment."))
        self.comboBox_2.setItemText(1, _translate("trimAl", "sgt: Print accumulated gap percentage count."))
        self.comboBox_2.setItemText(2, _translate("trimAl", "scc: Print conservation values for columns in the input alignment."))
        self.comboBox_2.setItemText(3, _translate("trimAl", "sct: Print accumulated conservation values count."))
        self.comboBox_2.setItemText(4, _translate("trimAl", "sfc: Print compare values for columns in the selected alignment from compare files method."))
        self.comboBox_2.setItemText(5, _translate("trimAl", "sft: Print accumulated compare values count for the selected alignment from compare files method."))
        self.comboBox_2.setItemText(6, _translate("trimAl", "sident: Print identity statistics for all sequences in the alignemnt."))
        self.checkBox_2.setText(_translate("trimAl", "colnumbering"))
        self.groupBox_3.setTitle(_translate("trimAl", "Run"))
        self.pushButton_2.setText(_translate("trimAl", "Stop"))
        self.pushButton.setText(_translate("trimAl", "Start"))
        self.groupBox.setTitle(_translate("trimAl", "Progress"))
        self.pushButton_9.setText(_translate("trimAl", "Show log"))

from src.CustomWidget import ArrowPushButton, ClickedLableGif, InputQLineEdit, ListQCombobox
from uifiles import myRes_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    trimAl = QtWidgets.QDialog()
    ui = Ui_trimAl()
    ui.setupUi(trimAl)
    trimAl.show()
    sys.exit(app.exec_())

