# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Work\python\bioinfo_excercise\PhyloSuite\PhyloSuite\PhyloSuite\uifiles\work_flow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WorkFlow(object):
    def setupUi(self, WorkFlow):
        WorkFlow.setObjectName("WorkFlow")
        WorkFlow.resize(605, 663)
        self.verticalLayout = QtWidgets.QVBoxLayout(WorkFlow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(WorkFlow)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.toolButton = QtWidgets.QToolButton(self.groupBox)
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture/resourses/add-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/picture/resourses/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setAutoRaise(True)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout.addWidget(self.toolButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.widget_2 = QtWidgets.QWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("border-top: 1px solid gray;\n"
"margin-top: 10px;")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3.addWidget(self.widget_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/picture/resourses/mafft1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox.setIcon(icon2)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 1, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/picture/resourses/M.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_8.setIcon(icon3)
        self.checkBox_8.setChecked(False)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout.addWidget(self.checkBox_8, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(163, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/picture/resourses/if_simpline_22_2305632.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_3.setIcon(icon4)
        self.checkBox_3.setChecked(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 1, 1, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/picture/resourses/icon--trim-confirm-0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_9.setIcon(icon5)
        self.checkBox_9.setChecked(False)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout.addWidget(self.checkBox_9, 1, 2, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/picture/resourses/clean.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_10.setIcon(icon6)
        self.checkBox_10.setChecked(False)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout.addWidget(self.checkBox_10, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 5, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/picture/resourses/cat1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_2.setIcon(icon7)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 2, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/picture/resourses/if_tinder_334781.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_5.setIcon(icon8)
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.buttonGroup = QtWidgets.QButtonGroup(WorkFlow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.checkBox_5)
        self.gridLayout.addWidget(self.checkBox_5, 2, 2, 1, 2)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/picture/resourses/pie-chart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_4.setIcon(icon9)
        self.checkBox_4.setObjectName("checkBox_4")
        self.buttonGroup.addButton(self.checkBox_4)
        self.gridLayout.addWidget(self.checkBox_4, 2, 4, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(163, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 6, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/picture/resourses/data-taxonomy-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_6.setIcon(icon10)
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 3, 1, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/picture/resourses/2000px-Paris_RER_B_icon.svg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_7.setIcon(icon11)
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(198, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 3, 1, 3)
        self.label_2 = ClickedLableGif(self.groupBox)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 6, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.listWidget_workflow = QtWidgets.QListWidget(WorkFlow)
        self.listWidget_workflow.setObjectName("listWidget_workflow")
        self.verticalLayout.addWidget(self.listWidget_workflow)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = ArrowPushButton(WorkFlow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/picture/resourses/if_start_60207.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon12)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_6 = QtWidgets.QPushButton(WorkFlow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/picture/resourses/if_Delete_1493279.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon13)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(WorkFlow)
        QtCore.QMetaObject.connectSlotsByName(WorkFlow)

    def retranslateUi(self, WorkFlow):
        _translate = QtCore.QCoreApplication.translate
        WorkFlow.setWindowTitle(_translate("WorkFlow", "Fast Phylogenetic Workflow"))
        self.groupBox.setTitle(_translate("WorkFlow", "Analyses"))
        self.label.setText(_translate("WorkFlow", "Workflow:"))
        self.toolButton.setToolTip(_translate("WorkFlow", "Add current settings to workflow"))
        self.toolButton_2.setToolTip(_translate("WorkFlow", "Delete current workflow"))
        self.label_7.setText(_translate("WorkFlow", "Select analyses to add them to the queue"))
        self.label_4.setText(_translate("WorkFlow", "Sequence Alignment:"))
        self.checkBox.setText(_translate("WorkFlow", "MAFFT"))
        self.checkBox_8.setText(_translate("WorkFlow", "MACSE"))
        self.label_8.setText(_translate("WorkFlow", "Alignment cleaning:"))
        self.checkBox_3.setText(_translate("WorkFlow", "Gblocks"))
        self.checkBox_9.setText(_translate("WorkFlow", "trimAl"))
        self.checkBox_10.setText(_translate("WorkFlow", "HmmCleaner"))
        self.label_5.setText(_translate("WorkFlow", "Model Selection:"))
        self.checkBox_2.setText(_translate("WorkFlow", "Concatenation"))
        self.checkBox_5.setText(_translate("WorkFlow", "ModelFinder"))
        self.checkBox_4.setText(_translate("WorkFlow", "PartitionFinder"))
        self.label_6.setText(_translate("WorkFlow", "Tree Reconstruction:"))
        self.checkBox_6.setText(_translate("WorkFlow", "IQ-TREE"))
        self.checkBox_7.setText(_translate("WorkFlow", "MrBayes"))
        self.label_2.setToolTip(_translate("WorkFlow", "Brief example"))
        self.pushButton.setText(_translate("WorkFlow", "Check | Start"))
        self.pushButton_6.setText(_translate("WorkFlow", "Stop"))

from src.CustomWidget import ArrowPushButton, ClickedLableGif
from uifiles import myRes_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WorkFlow = QtWidgets.QDialog()
    ui = Ui_WorkFlow()
    ui.setupUi(WorkFlow)
    WorkFlow.show()
    sys.exit(app.exec_())

