# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\softwares\python367\Lib\site-packages\ete3\treeview\annotation_editor2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_annotation_editor(object):
    def setupUi(self, annotation_editor):
        annotation_editor.setObjectName("annotation_editor")
        annotation_editor.resize(902, 667)
        self.verticalLayout = QtWidgets.QVBoxLayout(annotation_editor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(annotation_editor)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableView = MyTableView(annotation_editor)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(annotation_editor)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(annotation_editor)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ete icons/add-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(annotation_editor)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(annotation_editor)
        QtCore.QMetaObject.connectSlotsByName(annotation_editor)

    def retranslateUi(self, annotation_editor):
        _translate = QtCore.QCoreApplication.translate
        annotation_editor.setWindowTitle(_translate("annotation_editor", "Annotation editor"))
        self.label_2.setText(_translate("annotation_editor", "Pie chart:"))
        self.label.setText(_translate("annotation_editor", "Double click to modify data and header | Data can be pasted from or copied to Excel"))
        self.pushButton_2.setText(_translate("annotation_editor", "Add column"))
        self.pushButton.setText(_translate("annotation_editor", "Create"))
from .CustomWidgets import MyTableView
from . import ete_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    annotation_editor = QtWidgets.QDialog()
    ui = Ui_annotation_editor()
    ui.setupUi(annotation_editor)
    annotation_editor.show()
    sys.exit(app.exec_())
