# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\F\Work\python\bioinfo_excercise\PhyloSuite\codes\PhyloSuite\ete3\treeview\annotation_selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_annotation_selector(object):
    def setupUi(self, annotation_selector):
        annotation_selector.setObjectName("annotation_selector")
        annotation_selector.resize(298, 107)
        self.verticalLayout = QtWidgets.QVBoxLayout(annotation_selector)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(annotation_selector)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(annotation_selector)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.checkBox = QtWidgets.QCheckBox(annotation_selector)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.pushButton = QtWidgets.QPushButton(annotation_selector)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(annotation_selector)
        QtCore.QMetaObject.connectSlotsByName(annotation_selector)

    def retranslateUi(self, annotation_selector):
        _translate = QtCore.QCoreApplication.translate
        annotation_selector.setWindowTitle(_translate("annotation_selector", "Annotation selector"))
        self.label.setText(_translate("annotation_selector", "Select an annotation type:"))
        self.comboBox.setItemText(0, _translate("annotation_selector", "Auto-assign taxonomy (style 1)"))
        self.comboBox.setItemText(1, _translate("annotation_selector", "Auto-assign taxonomy (style 2)"))
        self.comboBox.setItemText(2, _translate("annotation_selector", "Leaf name"))
        self.comboBox.setItemText(3, _translate("annotation_selector", "Color strip"))
        self.comboBox.setItemText(4, _translate("annotation_selector", "Text"))
        self.comboBox.setItemText(5, _translate("annotation_selector", "Image"))
        self.comboBox.setItemText(6, _translate("annotation_selector", "Sequence"))
        self.comboBox.setItemText(7, _translate("annotation_selector", "Motif"))
        self.comboBox.setItemText(8, _translate("annotation_selector", "Horizontal bar chart"))
        self.comboBox.setItemText(9, _translate("annotation_selector", "Vertical bar chart"))
        self.comboBox.setItemText(10, _translate("annotation_selector", "Stacked bar chart"))
        self.comboBox.setItemText(11, _translate("annotation_selector", "Pie chart"))
        self.comboBox.setItemText(12, _translate("annotation_selector", "Heatmap"))
        self.comboBox.setItemText(13, _translate("annotation_selector", "Shape"))
        self.comboBox.setItemText(14, _translate("annotation_selector", "Attributes"))
        self.checkBox.setText(_translate("annotation_selector", "Include internal nodes"))
        self.pushButton.setText(_translate("annotation_selector", "Create"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    annotation_selector = QtWidgets.QDialog()
    ui = Ui_annotation_selector()
    ui.setupUi(annotation_selector)
    annotation_selector.show()
    sys.exit(app.exec_())
